import React, { createContext, useContext, useState, useEffect } from 'react';
import { Text, TextProps } from 'react-native';
import { Storage } from '../lib/storage';
import { INDIAN_LANGUAGES, IndianLanguage } from '../lib/languages';
import {
  initLanguageCache,
  translateText,
  getCachedTranslation,
} from '../services/translationService';

export type TranslationKey =
  | 'appName'
  | 'tagline'
  | 'farmersFirst'
  | 'brighterTomorrow'
  | 'heroDesc'
  | 'easyBooking'
  | 'noQueues'
  | 'fairPrices'
  | 'transparentMSP'
  | 'empowered'
  | 'digitalHassleFree'
  | 'welcomeTo'
  | 'signInGoogleDesc'
  | 'continueWithGoogle'
  | 'instantDemoLogin'
  | 'or'
  | 'securedBy'
  | 'transparent'
  | 'getFairPricesMsp'
  | 'bookMandiSlotsInMin'
  | 'digitalServicesEveryFarmer'
  | 'termsAgreement'
  | 'termsOfService'
  | 'privacyPolicy'
  | 'chooseLanguage'
  | 'selectPreferredLang'
  | 'skip'
  | 'next'
  | 'getStarted'
  | 'onboarding1Title'
  | 'onboarding1Highlight'
  | 'onboarding1Desc'
  | 'onboarding2Title'
  | 'onboarding2Highlight'
  | 'onboarding2Desc'
  | 'onboarding3Title'
  | 'onboarding3Highlight'
  | 'onboarding3Desc'
  | 'onboarding4Title'
  | 'onboarding4Highlight'
  | 'onboarding4Desc'
  | 'greetingNamaste'
  | 'goodToSeeYou'
  | 'makeFarmingRewarding'
  | 'farmerSlogan'
  | 'activeBookings'
  | 'queuePosition'
  | 'pendingPayments'
  | 'totalProcured'
  | 'spotlightActive'
  | 'spotlightCompleted'
  | 'viewAll'
  | 'noActiveBookings'
  | 'noActiveBookingsDesc'
  | 'bookNewSlot'
  | 'quickActions'
  | 'bookSlot'
  | 'liveQueue'
  | 'myPayments'
  | 'govtSchemes'
  | 'mspRates';

const TRANSLATIONS: Record<string, Record<TranslationKey, string>> = {
  en: {
    appName: 'KisanQueue',
    tagline: 'Smart Mandi. Fair Prices. Better Tomorrow.',
    farmersFirst: 'Farmers First',
    brighterTomorrow: 'A Brighter Tomorrow',
    heroDesc: 'Book mandi slots, track your produce, get fair prices — all in one app.',
    easyBooking: 'Easy Booking',
    noQueues: 'No long queues',
    fairPrices: 'Fair Prices',
    transparentMSP: 'Transparent MSP',
    empowered: 'Empowered',
    digitalHassleFree: 'Digital & Hassle Free',
    welcomeTo: 'Welcome to',
    signInGoogleDesc: 'Sign in with your Google account to get started',
    continueWithGoogle: 'Continue with Google',
    instantDemoLogin: 'Instant Demo Login (1-Tap)',
    or: 'OR',
    securedBy: 'Secured by Google & Firebase Authentication',
    transparent: 'Transparent',
    getFairPricesMsp: 'Get fair prices\nwith MSP',
    bookMandiSlotsInMin: 'Book mandi slots\nin minutes',
    digitalServicesEveryFarmer: 'Digital services\nfor every farmer',
    termsAgreement: "By continuing, you agree to KisanQueue's",
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    chooseLanguage: 'Choose Language',
    selectPreferredLang: 'Select your preferred language',
    skip: 'Skip',
    next: 'Next',
    getStarted: 'Get Started',
    onboarding1Title: 'Mandi me bina line lage',
    onboarding1Highlight: 'slot book karo',
    onboarding1Desc: 'Save time, book your APMC mandi entry slot effortlessly in 2 minutes.',
    onboarding2Title: 'Digital weighment,',
    onboarding2Highlight: 'transparent MSP payment',
    onboarding2Desc: 'Accurate weight, guaranteed MSP direct into your bank account with zero deductions.',
    onboarding3Title: 'Real-time queue',
    onboarding3Highlight: 'tracking on your phone',
    onboarding3Desc: 'Check live token position, estimated wait time and avoid mandi crowd.',
    onboarding4Title: 'Government schemes &',
    onboarding4Highlight: 'DigiLocker KYC',
    onboarding4Desc: 'Instant subsidy eligibility, PM-Kisan tracking and 1-click verified KYC.',
    greetingNamaste: 'Namaste',
    goodToSeeYou: 'Good to see you again',
    makeFarmingRewarding: "Let's make farming more rewarding today.",
    farmerSlogan: '🌾 Kisan Ki Mehnat, Desh Ki Shakti 🌾',
    activeBookings: 'Active Bookings',
    queuePosition: 'Queue Position',
    pendingPayments: 'Pending Payments',
    totalProcured: 'Total Procured',
    spotlightActive: 'Active Booking',
    spotlightCompleted: 'Procurement Completed',
    viewAll: 'View All ›',
    noActiveBookings: 'No Active Bookings',
    noActiveBookingsDesc: 'You have not booked any mandi slot yet. Book a new slot to sell produce.',
    bookNewSlot: '🌱 Book New Slot',
    quickActions: 'Quick Actions',
    bookSlot: 'Book Slot',
    liveQueue: 'Live Queue',
    myPayments: 'My Payments',
    govtSchemes: 'Govt Schemes',
    mspRates: 'MSP Rates (2026-27)',




  },

  hi: {
    appName: 'किसानकतार',
    tagline: 'स्मार्ट मंडी। सही दाम। बेहतर कल।',
    farmersFirst: 'किसान पहले',
    brighterTomorrow: 'उज्ज्वल कल',
    heroDesc: 'मंडी स्लॉट बुक करें, अपनी उपज ट्रैक करें, सही दाम पाएं — सब एक ऐप में।',
    easyBooking: 'आसान बुकिंग',
    noQueues: 'लंबी लाइनें नहीं',
    fairPrices: 'उचित मूल्य',
    transparentMSP: 'पारदर्शी एमएसपी',
    empowered: 'सशक्त किसान',
    digitalHassleFree: 'डिजिटल और झंझट-मुक्त',
    welcomeTo: 'स्वागत है',
    signInGoogleDesc: 'शुरू करने के लिए अपने गूगल अकाउंट से साइन इन करें',
    continueWithGoogle: 'गूगल के साथ जारी रखें',
    instantDemoLogin: 'त्वरित डेमो लॉगिन (1-टैप)',
    or: 'या',
    securedBy: 'गूगल और फायरबेस प्रमाणीकरण द्वारा सुरक्षित',
    transparent: 'पारदर्शी',
    getFairPricesMsp: 'एमएसपी के साथ\nउचित मूल्य पाएं',
    bookMandiSlotsInMin: 'मिनटों में मंडी\nस्लॉट बुक करें',
    digitalServicesEveryFarmer: 'हर किसान के लिए\nडिजिटल सेवाएं',
    termsAgreement: 'जारी रखकर, आप KisanQueue की',
    termsOfService: 'सेवा की शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
    chooseLanguage: 'भाषा चुनें',
    selectPreferredLang: 'अपनी पसंदीदा भाषा का चयन करें',
    skip: 'छोड़ें',
    next: 'आगे बढ़ें',
    getStarted: 'शुरू करें',
    onboarding1Title: 'मंडी में बिना लाइन लगे',
    onboarding1Highlight: 'स्लॉट बुक करें',
    onboarding1Desc: 'अपना समय बचाएं, आसानी से अपनी मंडी का टोकन स्लॉट बुक करें।',
    onboarding2Title: 'डिजिटल तौल,',
    onboarding2Highlight: 'पारदर्शी एमएसपी भुगतान',
    onboarding2Desc: 'सही तौल, सही दाम, बिना किसी कटौती के सीधे आपके बैंक खाते में।',
    onboarding3Title: 'लाइव कतार',
    onboarding3Highlight: 'ट्रैकिंग आपके फोन पर',
    onboarding3Desc: 'अपनी पोजीशन, अनुमानित समय लाइव देखें और मंडी भीड़ से बचें।',
    onboarding4Title: 'सरकारी योजनाएं और',
    onboarding4Highlight: 'डिजीलॉकर केवाईसी',
    onboarding4Desc: 'सरकारी योजनाओं की जानकारी, पात्रता जांच और आसान डिजिटल सत्यापन।',
    greetingNamaste: 'नमस्ते',
    goodToSeeYou: 'आपको देखकर खुशी हुई',
    makeFarmingRewarding: 'आइए आज खेती को और अधिक लाभकारी बनाएं।',
    farmerSlogan: '🌾 किसान की मेहनत, देश की शक्ति 🌾',
    activeBookings: 'सक्रिय बुकिंग्स',
    queuePosition: 'कतार स्थिति',
    pendingPayments: 'लंबित भुगतान',
    totalProcured: 'कुल खरीद',
    spotlightActive: 'सक्रिय बुकिंग',
    spotlightCompleted: 'खरीद पूरी हुई',
    viewAll: 'सभी देखें ›',
    noActiveBookings: 'कोई सक्रिय बुकिंग नहीं',
    noActiveBookingsDesc: 'आपने अभी कोई मंडी स्लॉट बुक नहीं किया है। फसल बेचने के लिए नया स्लॉट बुक करें।',
    bookNewSlot: '🌱 नया स्लॉट बुक करें',
    quickActions: 'त्वरित सेवाएं',
    bookSlot: 'स्लॉट बुक करें',
    liveQueue: 'लाइव कतार',
    myPayments: 'भुगतान विवरण',
    govtSchemes: 'सरकारी योजनाएं',
    mspRates: 'एमएसपी दरें (2026-27)',




  },

  pa: {
    appName: 'ਕਿਸਾਨਕਤਾਰ',
    tagline: 'ਸਮਾਰਟ ਮੰਡੀ। ਸਹੀ ਮੁੱਲ। ਬਿਹਤਰ ਭਲਕ।',
    farmersFirst: 'ਕਿਸਾਨ ਪਹਿਲਾਂ',
    brighterTomorrow: 'ਸੁਨਹਿਰੀ ਭਵਿੱਖ',
    heroDesc: 'ਮੰਡੀ ਸਲਾਟ ਬੁੱਕ ਕਰੋ, ਫਸਲ ਟ੍ਰੈਕ ਕਰੋ, ਸਹੀ ਮੁੱਲ ਪਾਓ — ਸਭ ਇੱਕੋ ਐਪ ਵਿੱਚ।',
    easyBooking: 'ਸੌਖੀ ਬੁਕਿੰਗ',
    noQueues: 'ਲੰਬੀਆਂ ਲਾਈਨਾਂ ਨਹੀਂ',
    fairPrices: 'ਸਹੀ ਮੁੱਲ',
    transparentMSP: 'ਪਾਰਦਰਸ਼ੀ ਐਮਐਸਪੀ',
    empowered: 'ਸਮਰੱਥ ਕਿਸਾਨ',
    digitalHassleFree: 'ਡਿਜੀਟਲ ਤੇ ਅਸਾਨ',
    welcomeTo: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    signInGoogleDesc: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਗੂਗਲ ਖਾਤੇ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    continueWithGoogle: 'ਗੂਗਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    instantDemoLogin: 'ਤੁਰੰਤ ਡੈਮੋ ਲੌਗਇਨ (1-ਟੈਪ)',
    or: 'ਜਾਂ',
    securedBy: 'ਗੂਗਲ ਤੇ ਫਾਇਰਬੇਸ ਨਾਲ ਸੁਰੱਖਿਅਤ',
    transparent: 'ਪਾਰਦਰਸ਼ੀ',
    getFairPricesMsp: 'ਐਮਐਸਪੀ ਨਾਲ\nਸਹੀ ਮੁੱਲ ਪਾਓ',
    bookMandiSlotsInMin: 'ਮਿੰਟਾਂ ਵਿੱਚ ਮੰਡੀ\nਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    digitalServicesEveryFarmer: 'ਹਰ ਕਿਸਾਨ ਲਈ\nਡਿਜੀਟਲ ਸੇਵਾਵਾਂ',
    termsAgreement: 'ਜਾਰੀ ਰੱਖ ਕੇ, ਤੁਸੀਂ ਸਹਿਮਤ ਹੁੰਦੇ ਹੋ',
    termsOfService: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    selectPreferredLang: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
    skip: 'ਛੱਡੋ',
    next: 'ਅੱਗੇ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    onboarding1Title: 'ਮੰਡੀ ਵਿੱਚ ਬਿਨਾਂ ਲਾਈਨ ਲੱਗੇ',
    onboarding1Highlight: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    onboarding1Desc: 'ਸਮਾਂ ਬਚਾਓ, ਆਪਣਾ ਮੰਡੀ ਐਂਟਰੀ ਸਲਾਟ 2 ਮਿੰਟ ਵਿੱਚ ਬੁੱਕ ਕਰੋ।',
    onboarding2Title: 'ਡਿਜੀਟਲ ਤੋਲ,',
    onboarding2Highlight: 'ਸਿੱਧਾ ਐਮਐਸਪੀ ਭੁਗਤਾਨ',
    onboarding2Desc: 'ਸਹੀ ਤੋਲ, ਗਾਰੰਟੀਸ਼ੁਦਾ ਐਮਐਸਪੀ ਸਿੱਧਾ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਬਿਨਾਂ ਕਟੌਤੀ।',
    onboarding3Title: 'ਰੀਅਲ-ਟਾਈਮ ਕਤਾਰ',
    onboarding3Highlight: 'ਮੋਬਾਈਲ ਤੇ ਲਾਈਵ ਟ੍ਰੈਕਿੰਗ',
    onboarding3Desc: 'ਲਾਈਵ ਟੋਕਨ ਸਥਿਤੀ ਅਤੇ ਅੰਦਾਜ਼ਨ ਸਮਾਂ ਦੇਖੋ, ਭੀੜ ਤੋਂ ਬਚੋ।',
    onboarding4Title: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਤੇ',
    onboarding4Highlight: 'ਡਿਜੀਲੌਕਰ ਕੇਵਾਈਸੀ',
    onboarding4Desc: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਦੀ ਜਾਣਕਾਰੀ ਅਤੇ ਸੌਖੀ ਡਿਜੀਟਲ ਪੜਤਾਲ।',
    greetingNamaste: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
    goodToSeeYou: 'ਤੁਹਾਨੂੰ ਦੁਬਾਰਾ ਵੇਖ ਕੇ ਖੁਸ਼ੀ ਹੋਈ',
    makeFarmingRewarding: 'ਆਓ ਅੱਜ ਖੇਤੀ ਨੂੰ ਹੋਰ ਲਾਭਦਾਇਕ ਬਣਾਈਏ।',
    farmerSlogan: '🌾 ਕਿਸਾਨ ਦੀ ਮਿਹਨਤ, ਦੇਸ਼ ਦੀ ਤਾਕਤ 🌾',
    activeBookings: 'ਐਕਟਿਵ ਬੁਕਿੰਗਾਂ',
    queuePosition: 'ਕਤਾਰ ਨੰਬਰ',
    pendingPayments: 'ਬਕਾਇਆ ਰਕਮ',
    totalProcured: 'ਕੁੱਲ ਖਰੀਦ',
    spotlightActive: 'ਐਕਟਿਵ ਬੁਕਿੰਗ',
    spotlightCompleted: 'ਖਰੀਦ ਮੁਕੰਮਲ',
    viewAll: 'ਸਾਰੇ ਵੇਖੋ ›',
    noActiveBookings: 'ਕੋਈ ਐਕਟਿਵ ਬੁਕਿੰਗ ਨਹੀਂ',
    noActiveBookingsDesc: 'ਤੁਸੀਂ ਅਜੇ ਕੋਈ ਮੰਡੀ ਸਲਾਟ ਬੁੱਕ ਨਹੀਂ ਕੀਤਾ। ਫਸਲ ਵੇਚਣ ਲਈ ਨਵਾਂ ਸਲਾਟ ਬੁੱਕ ਕਰੋ।',
    bookNewSlot: '🌱 ਨਵਾਂ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    quickActions: 'ਤੁਰੰਤ ਸੇਵਾਵਾਂ',
    bookSlot: 'ਸਲਾਟ ਬੁੱਕ',
    liveQueue: 'ਲਾਈਵ ਕਤਾਰ',
    myPayments: 'ਮੇਰੇ ਭੁਗਤਾਨ',
    govtSchemes: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    mspRates: 'ਐਮਐਸਪੀ ਦਰਾਂ (2026-27)',




  },

  mr: {
    appName: 'किसानरांग',
    tagline: 'स्मार्ट बाजारपेठ. योग्य भाव. उज्ज्वल भविष्य.',
    farmersFirst: 'शेतकरी प्रथम',
    brighterTomorrow: 'उज्ज्वल भविष्य',
    heroDesc: 'मार्केट स्लॉट बुक करा, उत्पादन ट्रॅक करा, योग्य भाव मिळवा — एकाच ॲपमध्ये.',
    easyBooking: 'सुलभ बुकिंग',
    noQueues: 'रांगांची चिंता नाही',
    fairPrices: 'योग्य दर',
    transparentMSP: 'पारदर्शक हमीभाव',
    empowered: 'सशक्त शेतकरी',
    digitalHassleFree: 'डिजिटल आणि सुलभ',
    welcomeTo: 'स्वागत आहे',
    signInGoogleDesc: 'सुरू करण्यासाठी आपल्या Google खात्याने साइन इन करा',
    continueWithGoogle: 'Google सह पुढे जा',
    instantDemoLogin: 'झटपट डेमो लॉगिन (1-टॅप)',
    or: 'किंवा',
    securedBy: 'Google आणि Firebase द्वारे सुरक्षित',
    transparent: 'पारदर्शक',
    getFairPricesMsp: 'हमीभावासह\nयोग्य दर मिळवा',
    bookMandiSlotsInMin: 'काही मिनिटांत\nमार्केट स्लॉट बुक करा',
    digitalServicesEveryFarmer: 'प्रत्येक शेतकऱ्यासाठी\nडिजिटल सेवा',
    termsAgreement: 'पुढे जाऊन, आपण सहमत आहात',
    termsOfService: 'सेवा अटी',
    privacyPolicy: 'गोपनीयता धोरण',
    chooseLanguage: 'भाषा निवडा',
    selectPreferredLang: 'आपली पसंतीची भाषा निवडा',
    skip: 'वगळा',
    next: 'पुढे',
    getStarted: 'सुरू करा',
    onboarding1Title: 'मार्केटमध्ये रांगेत न थांबता',
    onboarding1Highlight: 'स्लॉट बुक करा',
    onboarding1Desc: 'वेळ वाचवा, सहजतेने आपला मार्केट प्रवेश स्लॉट बुक करा.',
    onboarding2Title: 'डिजिटल वजन,',
    onboarding2Highlight: 'पारदर्शक हमीभाव जमा',
    onboarding2Desc: 'अचूक वजन, थेट आपल्या बँक खात्यात हमीभाव रक्कम.',
    onboarding3Title: 'रिअल-टाइम रांग',
    onboarding3Highlight: 'फोनवर थेट ट्रॅकिंग',
    onboarding3Desc: 'आपला नंबर आणि अंदाजे वेळ थेट पहा आणि गर्दी टाळा.',
    onboarding4Title: 'सरकारी योजना आणि',
    onboarding4Highlight: 'डिजिलॉकर केवायसी',
    onboarding4Desc: 'सरकारी योजनांची माहिती आणि जलद डिजिटल पडताळणी.',
    greetingNamaste: 'नमस्कार',
    goodToSeeYou: 'पुन्हा भेटून आनंद झाला',
    makeFarmingRewarding: 'चला शेती अधिक फायदेशीर बनवूया.',
    farmerSlogan: '🌾 शेतकऱ्यांचे श्रम, देशाची ताकद 🌾',
    activeBookings: 'सक्रिय बुकिंग',
    queuePosition: 'रांगेतील स्थान',
    pendingPayments: 'प्रलंबित देयके',
    totalProcured: 'एकूण खरेदी',
    spotlightActive: 'सक्रिय बुकिंग',
    spotlightCompleted: 'खरेदी पूर्ण झाली',
    viewAll: 'सर्व पहा ›',
    noActiveBookings: 'सक्रिय बुकिंग नाही',
    noActiveBookingsDesc: 'तुम्ही अद्याप कोणताही मार्केट स्लॉट बुक केलेला नाही. नवीन स्लॉट बुक करा.',
    bookNewSlot: '🌱 नवीन स्लॉट बुक करा',
    quickActions: 'जलद सेवा',
    bookSlot: 'स्लॉट बुकिंग',
    liveQueue: 'थेट रांग',
    myPayments: 'माझी देयके',
    govtSchemes: 'शासकीय योजना',
    mspRates: 'हमीभाव दर (2026-27)',




  },

  gu: {
    appName: 'કિસાનકતાર',
    tagline: 'સ્માર્ટ માર્કેટ. યોગ્ય ભાવ. ઉજ્જવળ આવતીકાલ.',
    farmersFirst: 'ખેડૂત પ્રથમ',
    brighterTomorrow: 'ઉજ્જવળ આવતીકાલ',
    heroDesc: 'માર્કેટિંગ યાર્ડ સ્લોટ બુક કરો, પાક ટ્રેક કરો, સાચા ભાવ મેળવો — એક જ ઍપમાં.',
    easyBooking: 'સરળ બુકિંગ',
    noQueues: 'લાંબી લાઈનો નહીં',
    fairPrices: 'સાચા ભાવ',
    transparentMSP: 'પારદર્શક ટેકાના ભાવ',
    empowered: 'સક્ષમ ખેડૂત',
    digitalHassleFree: 'ડિજિટલ અને ઝંઝટમુક્ત',
    welcomeTo: 'સ્વાગત છે',
    signInGoogleDesc: 'શરૂ કરવા માટે Google એકાઉન્ટથી સાઇન ઇન કરો',
    continueWithGoogle: 'Google સાથે આગળ વધો',
    instantDemoLogin: 'ઇન્સ્ટન્ટ ડેમો લૉગિન (1-ટૅપ)',
    or: 'અથવા',
    securedBy: 'Google અને Firebase દ્વારા સુરક્ષિત',
    transparent: 'પારદર્શક',
    getFairPricesMsp: 'ટેકાના ભાવ સાથે\nસાચા ભાવ મેળવો',
    bookMandiSlotsInMin: 'મિનિટોમાં યાર્ડ\nસ્લોટ બુક કરો',
    digitalServicesEveryFarmer: 'દરેક ખેડૂત માટે\nડિજિટલ સેવાઓ',
    termsAgreement: 'આગળ વધીને, તમે સંમત થાઓ છો',
    termsOfService: 'સેવાની શરતો',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    chooseLanguage: 'ભાષા પસંદ કરો',
    selectPreferredLang: 'તમારી પસંદગીની ભાષા પસંદ કરો',
    skip: 'છોડો',
    next: 'આગળ',
    getStarted: 'શરૂ કરો',
    onboarding1Title: 'યાર્ડમાં લાઈનમાં ઊભા રહ્યા વિના',
    onboarding1Highlight: 'સ્લોટ બુક કરો',
    onboarding1Desc: 'સમય બચાવો, સરળતાથી તમારો યાર્ડ સ્લોટ બુક કરો.',
    onboarding2Title: 'ડિજિટલ વજન,',
    onboarding2Highlight: 'સીધું ખાતામાં ચુકવણું',
    onboarding2Desc: 'સાચું વજન, સાચા ટેકાના ભાવ સીધા તમારા બેંક ખાતામાં.',
    onboarding3Title: 'રિયલ-ટાઇમ લાઇન',
    onboarding3Highlight: 'મોબાઇલ પર લાઇવ ટ્રેકિંગ',
    onboarding3Desc: 'તમારો નંબર અને સમય લાઇવ જુઓ અને ભીડથી બચો.',
    onboarding4Title: 'સરકારી યોજનાઓ અને',
    onboarding4Highlight: 'ડિજીલૉકર KYC',
    onboarding4Desc: 'સરકારી યોજનાઓની સંપૂર્ણ માહિતી અને સરળ ડિજિટલ ચકાસણી.',
    greetingNamaste: 'નમસ્તે',
    goodToSeeYou: 'તમને જોઈને આનંદ થયો',
    makeFarmingRewarding: 'ચાલો આજે ખેતીને વધુ નફાકારક બનાવીએ.',
    farmerSlogan: '🌾 ખેડૂતની મહેનત, દેશની તાકાત 🌾',
    activeBookings: 'સક્રિય બુકિંગ',
    queuePosition: 'લાઈનમાં નંબર',
    pendingPayments: 'બાકી ચૂકવણી',
    totalProcured: 'કુલ ખરીદી',
    spotlightActive: 'સક્રિય બુકિંગ',
    spotlightCompleted: 'ખરીદી પૂર્ણ',
    viewAll: 'બધું જુઓ ›',
    noActiveBookings: 'કોઈ સક્રિય બુકિંગ નથી',
    noActiveBookingsDesc: 'તમે હજી સુધી કોઈ માર્કેટ સ્લોટ બુક કર્યો નથી. નવો સ્લોટ બુક કરો.',
    bookNewSlot: '🌱 નવો સ્લોટ બુક કરો',
    quickActions: 'ઝડપી સેવાઓ',
    bookSlot: 'સ્લોટ બુકિંગ',
    liveQueue: 'લાઈવ લાઈન',
    myPayments: 'ચૂકવણી વિગતો',
    govtSchemes: 'સરકારી યોજનાઓ',
    mspRates: 'ટેકાના ભાવ (2026-27)',




  },

  te: {
    appName: 'కిసాన్ క్యూ',
    tagline: 'స్మార్ట్ మార్కెట్. సరసమైన ధరలు. మెరుగైన భవిష్యత్తు.',
    farmersFirst: 'రైతులే ప్రథమం',
    brighterTomorrow: 'ఉజ్వల భవిష్యత్తు',
    heroDesc: 'మార్కెట్ స్లాట్ బుక్ చేయండి, ఉత్పత్తులను ట్రాక్ చేయండి, సరసమైన ధరలు పొందండి.',
    easyBooking: 'సులభమైన బుకింగ్',
    noQueues: 'పొడవైన క్యూలు లేవు',
    fairPrices: 'సరసమైన ధరలు',
    transparentMSP: 'పారదర్శక MSP',
    empowered: 'సాధికారత',
    digitalHassleFree: 'డిజిటల్ & సులభం',
    welcomeTo: 'స్వాగతం',
    signInGoogleDesc: 'ప్రారంభించడానికి మీ Google ఖాతాతో సైన్ ఇన్ చేయండి',
    continueWithGoogle: 'Google తో కొనసాగించండి',
    instantDemoLogin: 'తక్షణ డెమో లాగిన్ (1-ట్యాప్)',
    or: 'లేదా',
    securedBy: 'Google & Firebase ద్వారా సురక్షితం',
    transparent: 'పారదర్శకం',
    getFairPricesMsp: 'MSP తో\nసరసమైన ధరలు',
    bookMandiSlotsInMin: 'నిమిషాల్లో స్లాట్\nబుక్ చేయండి',
    digitalServicesEveryFarmer: 'ప్రతి రైతుకు\nడిజిటల్ సేవలు',
    termsAgreement: 'కొనసాగడం ద్వారా మీరు అంగీకరిస్తున్నారు',
    termsOfService: 'సేవా నిబంధనలు',
    privacyPolicy: 'గోప్యతా విధానం',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    selectPreferredLang: 'మీ ప్రాధాన్యత గల భాషను ఎంచుకోండి',
    skip: 'దాటవేయి',
    next: 'తరువాత',
    getStarted: 'ప్రారంభించండి',
    onboarding1Title: 'మార్కెట్లో క్యూలో నిలబడకుండా',
    onboarding1Highlight: 'స్లాట్ బుక్ చేయండి',
    onboarding1Desc: 'సమయాన్ని ఆదా చేసుకోండి, మీ మార్కెట్ స్లాట్‌ను సులభంగా బుక్ చేయండి.',
    onboarding2Title: 'డిజిటల్ బరువు,',
    onboarding2Highlight: 'ఖాతాలోకి నేరుగా MSP',
    onboarding2Desc: 'ఖచ్చితమైన బరువు, కటింగ్ లేకుండా మీ బ్యాంకు ఖాతాలోకి నేరుగా నిధులు.',
    onboarding3Title: 'రియల్-టైమ్ క్యూ',
    onboarding3Highlight: 'ఫోన్ లో లైవ్ ట్రాకింగ్',
    onboarding3Desc: 'మీ టోకెన్ స్థితిని ప్రత్యక్షంగా ట్రాక్ చేయండి మరియు రద్దీని నివారించండి.',
    onboarding4Title: 'ప్రభుత్వ పథకాలు &',
    onboarding4Highlight: 'డిజిలాకర్ కేవైసీ',
    onboarding4Desc: 'అన్ని ప్రభుత్వ వ్యవసాయ పథకాలు మరియు సులభమైన ధృవీకరణ.',
    greetingNamaste: 'నమస్కారం',
    goodToSeeYou: 'మిమ్మల్ని మళ్ళీ కలవడం ఆనందంగా ఉంది',
    makeFarmingRewarding: 'వ్యవసాయాన్ని మరింత లాభదాయకంగా మార్చుకుందాం.',
    farmerSlogan: '🌾 రైతు శ్రమ, దేశానికి బలం 🌾',
    activeBookings: 'యాక్టివ్ బుకింగ్‌లు',
    queuePosition: 'క్యూ స్థానం',
    pendingPayments: 'పెండింగ్ చెల్లింపులు',
    totalProcured: 'మొత్తం సేకరణ',
    spotlightActive: 'యాక్టివ్ బుకింగ్',
    spotlightCompleted: 'సేకరణ పూర్తయింది',
    viewAll: 'అన్నీ చూడండి ›',
    noActiveBookings: 'యాక్టివ్ బుకింగ్‌లు లేవు',
    noActiveBookingsDesc: 'మీరు ఇంకా ఎటువంటి స్లాట్ బుక్ చేసుకోలేదు. కొత్త స్లాట్ బుక్ చేయండి.',
    bookNewSlot: '🌱 కొత్త స్లాట్ బుక్ చేయండి',
    quickActions: 'త్వరిత సేవలు',
    bookSlot: 'స్లాట్ బుక్',
    liveQueue: 'లైవ్ క్యూ',
    myPayments: 'చెల్లింపులు',
    govtSchemes: 'పథకాలు',
    mspRates: 'MSP ధరలు (2026-27)',




  },

  bn: {
    appName: 'কিষাণকিউ',
    tagline: 'স্মার্ট মান্ডি। ন্যায্য দাম। উজ্জ্বল ভবিষ্যৎ।',
    farmersFirst: 'কৃষক প্রথম',
    brighterTomorrow: 'উজ্জ্বল ভবিষ্যৎ',
    heroDesc: 'মান্ডি স্লট বুক করুন, ফসল ট্র্যাক করুন, ন্যায্য দাম পান — একটি অ্যাপেই।',
    easyBooking: 'সহজ বুকিং',
    noQueues: 'দীর্ঘ লাইনের ঝামেলা নেই',
    fairPrices: 'ন্যায্য দাম',
    transparentMSP: 'স্বচ্ছ এমএসপি',
    empowered: 'সশক্ত কৃষক',
    digitalHassleFree: 'ডিজিটাল ও সহজ',
    welcomeTo: 'স্বাগতম',
    signInGoogleDesc: 'শুরু করতে আপনার গুগল অ্যাকাউন্ট দিয়ে সাইন ইন করুন',
    continueWithGoogle: 'গুগল দিয়ে এগিয়ে যান',
    instantDemoLogin: 'তাত্ক্ষণিক ডেমো লগইন (১-ট্যাপ)',
    or: 'অথবা',
    securedBy: 'গুগল ও ফায়ারবেস দ্বারা সুরক্ষিত',
    transparent: 'স্বচ্ছ',
    getFairPricesMsp: 'এমএসপি সহ\nন্যায্য দাম পান',
    bookMandiSlotsInMin: 'মিনিটেই মান্ডি\nস্লট বুক করুন',
    digitalServicesEveryFarmer: 'প্রতিটি কৃষকের জন্য\nডিজিটাল সেবা',
    termsAgreement: 'চালিয়ে গিয়ে, আপনি সম্মত হচ্ছেন',
    termsOfService: 'সেবার শর্তাবলী',
    privacyPolicy: 'গোপনীয়তা নীতি',
    chooseLanguage: 'ভাষা নির্বাচন করুন',
    selectPreferredLang: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    skip: 'এড়িয়ে যান',
    next: 'পরবর্তী',
    getStarted: 'শুরু করুন',
    onboarding1Title: 'লাইনে না দাঁড়িয়ে মান্ডিতে',
    onboarding1Highlight: 'স্লট বুক করুন',
    onboarding1Desc: 'সময় বাঁচান, সহজেই আপনার মান্ডির এন্ট্রি স্লট বুক করুন।',
    onboarding2Title: 'ডিজিটাল ওজন,',
    onboarding2Highlight: 'স্বচ্ছ এমএসপি প্রদান',
    onboarding2Desc: 'সঠিক ওজন, সরাসরি আপনার ব্যাংক অ্যাকাউন্টে এমএসপি টাকা।',
    onboarding3Title: 'রিয়েল-টাইম কিউ',
    onboarding3Highlight: 'ফোনেই লাইভ ট্র্যাকিং',
    onboarding3Desc: 'আপনার অবস্থান ও আনুমানিক সময় লাইভ দেখুন ও ভিড় এড়ান।',
    onboarding4Title: 'সরকারি প্রকল্প ও',
    onboarding4Highlight: 'ডিজিলকার কেওয়াইসি',
    onboarding4Desc: 'সরকারি কৃষি প্রকল্পের তথ্য এবং সহজ ডিজিটাল যাচাইকরণ।',
    greetingNamaste: 'নমস্কার',
    goodToSeeYou: 'আপনাকে আবার দেখে ভালো লাগলো',
    makeFarmingRewarding: 'আসুন কৃষিকে আরও লাভজনক করি।',
    farmerSlogan: '🌾 কৃষকের ঘাম, দেশের সম্মান 🌾',
    activeBookings: 'সক্রিয় বুকিং',
    queuePosition: 'সিরিয়াল নম্বর',
    pendingPayments: 'বকেয়া টাকা',
    totalProcured: 'মোট ক্রয়',
    spotlightActive: 'সক্রিয় বুকিং',
    spotlightCompleted: 'ক্রয় সম্পন্ন',
    viewAll: 'সব দেখুন ›',
    noActiveBookings: 'কোনো সক্রিয় বুকিং নেই',
    noActiveBookingsDesc: 'আপনি এখনও কোনো মান্ডি স্লট বুক করেননি। ফসল বিক্রির জন্য নতুন স্লট বুক করুন।',
    bookNewSlot: '🌱 নতুন স্লট বুক করুন',
    quickActions: 'দ্রুত সেবা',
    bookSlot: 'স্লট বুক',
    liveQueue: 'লাইভ কিউ',
    myPayments: 'আমার পেমেন্ট',
    govtSchemes: 'সরকারি প্রকল্প',
    mspRates: 'এমএসপি দর (2026-27)',




  },

  ta: {
    appName: 'கிசான்கியூ',
    tagline: 'ஸ்மார்ட் மண்டி. நியாயமான விலை. சிறந்த எதிர்காலம்.',
    farmersFirst: 'விவசாயிகள் முதலில்',
    brighterTomorrow: 'சிறந்த எதிர்காலம்',
    heroDesc: 'மண்டி ஸ்லாட் முன்பதிவு, பயிர் கண்காணிப்பு, நியாயமான விலை — ஒரே செயலியில்.',
    easyBooking: 'எளிய முன்பதிவு',
    noQueues: 'நீண்ட வரிசைகள் இல்லை',
    fairPrices: 'நியாயமான விலை',
    transparentMSP: 'வெளிப்படையான MSP',
    empowered: 'வலுவான விவசாயி',
    digitalHassleFree: 'டிஜிட்டல் மற்றும் சுலபம்',
    welcomeTo: 'வரவேற்கிறோம்',
    signInGoogleDesc: 'தொடங்க உங்கள் கூகிள் கணக்கு மூலம் உள்நுழைக',
    continueWithGoogle: 'கூகிள் மூலம் தொடரவும்',
    instantDemoLogin: 'உடனடி டெமோ உள்நுழைவு (1-தட்டு)',
    or: 'அல்லது',
    securedBy: 'Google & Firebase மூலம் பாதுகாக்கப்பட்டது',
    transparent: 'வெளிப்படையானது',
    getFairPricesMsp: 'MSP மூலம்\nநியாயமான விலை',
    bookMandiSlotsInMin: 'நிமிடங்களில் ஸ்லாட்\nமுன்பதிவு செய்யுங்கள்',
    digitalServicesEveryFarmer: 'ஒவ்வொரு விவசாயிக்கும்\nடிஜிட்டல் சேவை',
    termsAgreement: 'தொடர்வதன் மூலம் நீங்கள் ஒப்புக்கொள்கிறீர்கள்',
    termsOfService: 'சேவை விதிமுறைகள்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    selectPreferredLang: 'உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
    skip: 'தவிர்',
    next: 'அடுத்து',
    getStarted: 'தொடங்கவும்',
    onboarding1Title: 'வரிசையில் நிற்காமல் மண்டியில்',
    onboarding1Highlight: 'ஸ்லாட் முன்பதிவு செய்க',
    onboarding1Desc: 'நேரத்தை மிச்சப்படுத்துங்கள், மண்டி நுழைவு ஸ்லாட்டை எளிதாக பதிவு செய்க.',
    onboarding2Title: 'டிஜிட்டல் எடை,',
    onboarding2Highlight: 'நேரடி MSP பணம்',
    onboarding2Desc: 'துல்லியமான எடை, வங்கி கணக்கில் நேரடியாக முழு MSP பணம்.',
    onboarding3Title: 'நேரலை வரிசை',
    onboarding3Highlight: 'போனில் நேரலை கண்காணிப்பு',
    onboarding3Desc: 'டோக்கன் நிலை மற்றும் காத்திருப்பு நேரத்தை போனில் பாருங்கள்.',
    onboarding4Title: 'அரசு திட்டங்கள் &',
    onboarding4Highlight: 'டிஜிலாக்கர் KYC',
    onboarding4Desc: 'அனைத்து அரசு திட்டங்கள் மற்றும் எளிதான டிஜிட்டல் சரிபார்ப்பு.',
    greetingNamaste: 'வணக்கம்',
    goodToSeeYou: 'மீண்டும் உங்களை சந்திப்பதில் மகிழ்ச்சி',
    makeFarmingRewarding: 'விவசாயத்தை மேலும் லாபகரமானதாக மாற்றுவோம்.',
    farmerSlogan: '🌾 உழவர் உழைப்பு, நாட்டின் பலம் 🌾',
    activeBookings: 'முன்பதிவுகள்',
    queuePosition: 'வரிசை நிலை',
    pendingPayments: 'நிலுவை தொகை',
    totalProcured: 'மொத்த கொள்முதல்',
    spotlightActive: 'செயலில் உள்ள முன்பதிவு',
    spotlightCompleted: 'கொள்முதல் முடிந்தது',
    viewAll: 'அனைத்தும் பார்க்க ›',
    noActiveBookings: 'முன்பதிவுகள் இல்லை',
    noActiveBookingsDesc: 'நீங்கள் இன்னும் ஸ்லாட் முன்பதிவு செய்யவில்லை. புதிய ஸ்லாட் பதிவு செய்யவும்.',
    bookNewSlot: '🌱 புதிய ஸ்லாட் பதிவு செய்க',
    quickActions: 'விரைவு சேவைகள்',
    bookSlot: 'ஸ்லாட் பதிவு',
    liveQueue: 'நேரலை வரிசை',
    myPayments: 'பணம் விவரம்',
    govtSchemes: 'அரசு திட்டங்கள்',
    mspRates: 'MSP விலை (2026-27)',




  },

  kn: {
    appName: 'ಕಿಸಾನ್‌ಕ್ಯೂ',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಮಾರುಕಟ್ಟೆ. ಸೂಕ್ತ ಬೆಲೆ. ಉತ್ತಮ ಭವಿಷ್ಯ.',
    farmersFirst: 'ರೈತನೇ ಮೊದಲು',
    brighterTomorrow: 'ಉಜ್ವಲ ಭವಿಷ್ಯ',
    heroDesc: 'ಮಾರುಕಟ್ಟೆ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ, ಬೆಳೆ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ನ್ಯಾಯಯುತ ಬೆಲೆ ಪಡೆಯಿರಿ.',
    easyBooking: 'ಸುಲಭ ಬುಕಿಂಗ್',
    noQueues: 'ಉದ್ದನೆಯ ಸಾಲುಗಳಿಲ್ಲ',
    fairPrices: 'ನ್ಯಾಯಯುತ ಬೆಲೆ',
    transparentMSP: 'ಪಾರದರ್ಶಕ MSP',
    empowered: 'ಸಶಕ್ತ ರೈತ',
    digitalHassleFree: 'ಡಿಜಿಟಲ್ & ಸರಳ',
    welcomeTo: 'ಸ್ವಾಗತ',
    signInGoogleDesc: 'ಪ್ರಾರಂಭಿಸಲು ಗೂಗಲ್ ಖಾತೆಯೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    continueWithGoogle: 'ಗೂಗಲ್ ಮುಖಾಂತರ ಮುಂದುವರಿಯಿರಿ',
    instantDemoLogin: 'ತ್ವರಿತ ಡೆಮೊ ಲಾಗಿನ್ (1-ಟ್ಯಾಪ್)',
    or: 'ಅಥವಾ',
    securedBy: 'ಗೂಗಲ್ ಮತ್ತು ಫೈರ್‌ಬೇಸ್ ಮೂಲಕ ಸುರಕ್ಷಿತ',
    transparent: 'ಪಾರದರ್ಶಕ',
    getFairPricesMsp: 'MSP ಯೊಂದಿಗೆ\nನ್ಯಾಯಯುತ ಬೆಲೆ ಪಡೆಯಿರಿ',
    bookMandiSlotsInMin: 'ನಿಮಿಷಗಳಲ್ಲಿ ಸ್ಲಾಟ್\nಬುಕ್ ಮಾಡಿ',
    digitalServicesEveryFarmer: 'ಪ್ರತಿಯೊಬ್ಬ ರೈತನಿಗಾಗಿ\nಡಿಜಿಟಲ್ ಸೇವೆಗಳು',
    termsAgreement: 'ಮುಂದುವರಿಯುವ ಮೂಲಕ ನೀವು ಒಪ್ಪುತ್ತೀರಿ',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    selectPreferredLang: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    next: 'ಮುಂದೆ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    onboarding1Title: 'ಸಾಲಿನಲ್ಲಿ ನಿಲ್ಲದೆ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ',
    onboarding1Highlight: 'ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ',
    onboarding1Desc: 'ಸಮಯ ಉಳಿಸಿ, ಸುಲಭವಾಗಿ ನಿಮ್ಮ ಪ್ರವೇಶ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ.',
    onboarding2Title: 'ಡಿಜಿಟಲ್ ತೂಕ,',
    onboarding2Highlight: 'ನೇರ MSP ಪಾವತಿ',
    onboarding2Desc: 'ನಿಖರ ತೂಕ, ನೇರವಾಗಿ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಹಣ ವರ್ಗಾವಣೆ.',
    onboarding3Title: 'ನೈಜ-ಸಮಯದ ಕ್ಯೂ',
    onboarding3Highlight: 'ಮೊಬೈಲ್‌ನಲ್ಲಿ ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    onboarding3Desc: 'ಟೋಕನ್ ಸ್ಥಿತಿ ಮತ್ತು ಕಾಯುವ ಸಮಯ ಲೈವ್ ಆಗಿ ವೀಕ್ಷಿಸಿ.',
    onboarding4Title: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು &',
    onboarding4Highlight: 'ಡಿಜಿಲಾಕರ್ ಕೆವೈಸಿ',
    onboarding4Desc: 'ಸರ್ಕಾರಿ ಕೃಷಿ ಯೋಜನೆಗಳ ಮಾಹಿತಿ ಮತ್ತು ಸುಲಭ ಪರಿಶೀಲನೆ.',
    greetingNamaste: 'ನಮಸ್ಕಾರ',
    goodToSeeYou: 'ನಿಮ್ಮನ್ನು ಮತ್ತೆ ಭೇಟಿಯಾಗಲು ಸಂತೋಷವಾಗಿದೆ',
    makeFarmingRewarding: 'ಕೃಷಿಯನ್ನು ಹೆಚ್ಚು ಲಾಭದಾಯಕವಾಗಿಸೋಣ.',
    farmerSlogan: '🌾 ರೈತನ ಬೆವರು, ದೇಶದ ಉಸಿರು 🌾',
    activeBookings: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು',
    queuePosition: 'ಕ್ಯೂ ಸಂಖ್ಯೆ',
    pendingPayments: 'ಬಾಕಿ ಪಾವತಿಗಳು',
    totalProcured: 'ಒಟ್ಟು ಖರೀದಿ',
    spotlightActive: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್',
    spotlightCompleted: 'ಖರೀದಿ ಪೂರ್ಣಗೊಂಡಿದೆ',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ ›',
    noActiveBookings: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಬುಕಿಂಗ್ ಇಲ್ಲ',
    noActiveBookingsDesc: 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿಲ್ಲ. ಹೊಸ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ.',
    bookNewSlot: '🌱 ಹೊಸ ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ',
    quickActions: 'ತ್ವರಿತ ಸೇವೆಗಳು',
    bookSlot: 'ಸ್ಲಾಟ್ ಬುಕಿಂಗ್',
    liveQueue: 'ಲೈವ್ ಕ್ಯೂ',
    myPayments: 'ನನ್ನ ಪಾವತಿಗಳು',
    govtSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    mspRates: 'MSP ದರಗಳು (2026-27)',




  },

  ml: {
    appName: 'കിസാൻക്യൂ',
    tagline: 'സ്മാർട്ട് മാർക്കറ്റ്. മികച്ച വില. മെച്ചപ്പെട്ട നാളെ.',
    farmersFirst: 'കർഷകർ ആദ്യം',
    brighterTomorrow: 'ഉജ്ജ്വല ഭാവം',
    heroDesc: 'മാർക്കറ്റ് സ്ലോട്ട് ബുക്ക് ചെയ്യുക, ഉൽപ്പാദനം ട്രാക്ക് ചെയ്യുക, മികച്ച വില ഉറപ്പാക്കുക.',
    easyBooking: 'എളുപ്പമുള്ള ബുക്കിംഗ്',
    noQueues: 'നീണ്ട ക്യൂവുകൾ ഇല്ല',
    fairPrices: 'ന്യായമായ വില',
    transparentMSP: 'സുതാര്യമായ MSP',
    empowered: 'ശാക്തീകരിച്ച കർഷകർ',
    digitalHassleFree: 'ഡിജിറ്റൽ & ലളിതം',
    welcomeTo: 'സ്വാഗതം',
    signInGoogleDesc: 'തുടങ്ങാൻ ഗൂഗിൾ അക്കൗണ്ട് ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    continueWithGoogle: 'ഗൂഗിൾ വഴി തുടരുക',
    instantDemoLogin: 'തൽക്ഷണ ഡെമോ ലോഗിൻ (1-ടാപ്പ്)',
    or: 'അല്ലെങ്കിൽ',
    securedBy: 'Google, Firebase എന്നിവയാൽ സുരക്ഷിതം',
    transparent: 'സുതാര്യം',
    getFairPricesMsp: 'MSP വഴി\nന്യായമായ വില നേടുക',
    bookMandiSlotsInMin: 'മിനിറ്റുകൾക്കുള്ളിൽ സ്ലോട്ട്\nബുക്ക് ചെയ്യാം',
    digitalServicesEveryFarmer: 'എല്ലാ കർഷകർക്കും\nഡിജിറ്റൽ സേവനങ്ങൾ',
    termsAgreement: 'തുടരുന്നതിലൂടെ നിങ്ങൾ അംഗീകരിക്കുന്നു',
    termsOfService: 'സേവന നിബന്ധനകൾ',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    selectPreferredLang: 'നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക',
    skip: 'ഒഴിവാക്കുക',
    next: 'അടുത്തത്',
    getStarted: 'ആരംഭിക്കുക',
    onboarding1Title: 'ക്യൂ നിൽക്കാതെ മാർക്കറ്റിൽ',
    onboarding1Highlight: 'സ്ലോട്ട് ബുക്ക് ചെയ്യുക',
    onboarding1Desc: 'സമയം ലാഭിക്കുക, നിങ്ങളുടെ മാർക്കറ്റ് പ്രവേശന സ്ലോട്ട് എളുപ്പത്തിൽ ബുക്ക് ചെയ്യുക.',
    onboarding2Title: 'ഡിജിറ്റൽ തൂക്കം,',
    onboarding2Highlight: 'നേരിട്ടുള്ള MSP പേയ്‌മെന്റ്',
    onboarding2Desc: 'കൃത്യമായ തൂക്കം, ബാങ്ക് അക്കൗണ്ടിലേക്ക് നേരിട്ട് പണം.',
    onboarding3Title: 'തത്സമയ ക്യൂ',
    onboarding3Highlight: 'ഫോണിൽ ലൈവ് ട്രാക്കിംഗ്',
    onboarding3Desc: 'ടോക്കൺ നിലയും കാത്തിരിപ്പ് സമയവും ഫോണിൽ നേരിട്ട് കാണാം.',
    onboarding4Title: 'സർക്കാർ പദ്ധതികൾ &',
    onboarding4Highlight: 'ഡിജിലോക്കർ കെവൈസി',
    onboarding4Desc: 'സർക്കാർ ആനുകൂല്യങ്ങളും എളുപ്പമുള്ള ഡിജിറ്റൽ പരിശോധനയും.',
    greetingNamaste: 'നമസ്കാരം',
    goodToSeeYou: 'വീണ്ടും കണ്ടതിൽ സന്തോഷം',
    makeFarmingRewarding: 'കൃഷി കൂടുതൽ ലാഭകരമാക്കാം.',
    farmerSlogan: '🌾 കർഷകന്റെ അധ്വാനം, നാടിന്റെ കരുത്ത് 🌾',
    activeBookings: 'സജീവ ബുക്കിംഗുകൾ',
    queuePosition: 'ക്യൂ സ്ഥാനം',
    pendingPayments: 'ലഭിക്കാനുള്ള തുക',
    totalProcured: 'ആകെ സംഭരണം',
    spotlightActive: 'സജീവ ബുക്കിംഗ്',
    spotlightCompleted: 'സംഭരണം പൂർത്തിയായി',
    viewAll: 'എല്ലാം കാണുക ›',
    noActiveBookings: 'സജീവ ബുക്കിംഗുകൾ ഇല്ല',
    noActiveBookingsDesc: 'നിങ്ങൾ ഇതുവരെ സ്ലോട്ട് ബുക്ക് ചെയ്തിട്ടില്ല. പുതിയ സ്ലോട്ട് ബുക്ക് ചെയ്യുക.',
    bookNewSlot: '🌱 പുതിയ സ്ലോട്ട് ബുക്ക് ചെയ്യുക',
    quickActions: 'ദ്രുത സേവനങ്ങൾ',
    bookSlot: 'സ്ലോട്ട് ബുക്കിംഗ്',
    liveQueue: 'ലൈവ് ക്യൂ',
    myPayments: 'പേയ്‌മെന്റുകൾ',
    govtSchemes: 'പദ്ധതികൾ',
    mspRates: 'MSP നിരക്കുകൾ (2026-27)',




  },

  or: {
    appName: 'କିଷାନକ୍ୟୁ',
    tagline: 'ସ୍ମାର୍ଟ ମଣ୍ଡି। ଉଚିତ ମୂଲ୍ୟ। ଉଜ୍ଜ୍ୱଳ ଭବିଷ୍ୟତ।',
    farmersFirst: 'କୃଷକ ପ୍ରଥମେ',
    brighterTomorrow: 'ଉଜ୍ଜ୍ୱଳ କାଲି',
    heroDesc: 'ମଣ୍ଡି ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ, ଫସଲ ଟ୍ରାକ୍ କରନ୍ତୁ, ସଠିକ୍ ଏମଏସପି ପାଆନ୍ତୁ।',
    easyBooking: 'ସହଜ ବୁକିଂ',
    noQueues: 'ଲମ୍ବା ଧାଡ଼ି ନାହିଁ',
    fairPrices: 'ଉଚିତ ମୂଲ୍ୟ',
    transparentMSP: 'ସ୍ୱଚ୍ଛ ଏମଏସପି',
    empowered: 'ସଶକ୍ତ କୃଷକ',
    digitalHassleFree: 'ଡିଜିଟାଲ୍ ଓ ସହଜ',
    welcomeTo: 'ସ୍ୱାଗତ',
    signInGoogleDesc: 'ଆରମ୍ଭ କରିବାକୁ ଗୁଗୁଲ୍ ଆକାଉଣ୍ଟ୍ ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    continueWithGoogle: 'ଗୁଗୁଲ୍ ସହିତ ଆଗକୁ ବଢ଼ନ୍ତୁ',
    instantDemoLogin: 'ତୁରନ୍ତ ଡେମୋ ଲଗଇନ୍ (1-ଟ୍ୟାପ୍)',
    or: 'କିମ୍ବା',
    securedBy: 'Google ଏବଂ Firebase ଦ୍ୱାରା ସୁରକ୍ଷିତ',
    transparent: 'ସ୍ୱଚ୍ଛ',
    getFairPricesMsp: 'ଏମଏସପି ସହିତ\nସଠିକ୍ ମୂଲ୍ୟ ପାଆନ୍ତୁ',
    bookMandiSlotsInMin: 'ମିନିଟରେ ମଣ୍ଡି\nସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ',
    digitalServicesEveryFarmer: 'ପ୍ରତ୍ୟେକ କୃଷକ ପାଇଁ\nଡିଜିଟାଲ୍ ସେବା',
    termsAgreement: 'ଆଗକୁ ବଢ଼ି, ଆପଣ ସହମତ ହେଉଛନ୍ତି',
    termsOfService: 'ସେବା ସର୍ତ୍ତାବଳୀ',
    privacyPolicy: 'ଗୋପନୀୟତା ନୀତି',
    chooseLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    selectPreferredLang: 'ଆପଣଙ୍କର ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ',
    skip: 'ଏଡ଼ାଇ ଯାଆନ୍ତୁ',
    next: 'ପରବର୍ତ୍ତୀ',
    getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
    onboarding1Title: 'ଧାଡ଼ିରେ ନଠିଆ ହୋଇ ମଣ୍ଡିରେ',
    onboarding1Highlight: 'ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ',
    onboarding1Desc: 'ସମୟ ବଞ୍ଚାନ୍ତୁ, ସହଜରେ ମଣ୍ଡି ପ୍ରବେଶ ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ।',
    onboarding2Title: 'ଡିଜିଟାଲ୍ ଓଜନ,',
    onboarding2Highlight: 'ସିଧାସଳଖ ଏମଏସପି ଦେୟ',
    onboarding2Desc: 'ସଠିକ୍ ଓଜନ, ବ୍ୟାଙ୍କ ଖାତାକୁ ସିଧାସଳଖ ସମ୍ପୂର୍ଣ୍ଣ ଏମଏସପି ଟଙ୍କା।',
    onboarding3Title: 'ଲାଇଭ୍ ଧାଡ଼ି',
    onboarding3Highlight: 'ଫୋନରେ ଲାଇଭ୍ ଟ୍ରାକିଂ',
    onboarding3Desc: 'ଟୋକନ୍ ସ୍ଥିତି ଏବଂ ସମୟ ଫୋନରେ ସିଧାସଳଖ ଦେଖନ୍ତୁ।',
    onboarding4Title: 'ସରକାରୀ ଯୋଜନା &',
    onboarding4Highlight: 'ଡିଜିଲକର୍ କେୱାଇସି',
    onboarding4Desc: 'ସମସ୍ତ ସରକାରୀ କୃଷି ଯୋଜନା ଏବଂ ସହଜ ଡିଜିଟାଲ୍ ଯାଞ୍ଚ।',
    greetingNamaste: 'ନମସ୍କାର',
    goodToSeeYou: 'ଆପଣଙ୍କୁ ଦେଖି ଖୁସି ଲାଗିଲା',
    makeFarmingRewarding: 'ଚାଷକୁ ଅଧିକ ଲାଭଦାୟକ କରିବା।',
    farmerSlogan: '🌾 ଚାଷୀର ପରିଶ୍ରମ, ଦେଶର ଶକ୍ତି 🌾',
    activeBookings: 'ସକ୍ରିୟ ବୁକିଂ',
    queuePosition: 'ଧାଡ଼ି ନମ୍ବର',
    pendingPayments: 'ବାକି ପେମେଣ୍ଟ',
    totalProcured: 'ମୋଟ କ୍ରୟ',
    spotlightActive: 'ସକ୍ରିୟ ବୁକିଂ',
    spotlightCompleted: 'କ୍ରୟ ସମ୍ପୂର୍ଣ୍ଣ',
    viewAll: 'ସବୁ ଦେଖନ୍ତୁ ›',
    noActiveBookings: 'କୌଣସି ସକ୍ରିୟ ବୁକିଂ ନାହିଁ',
    noActiveBookingsDesc: 'ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସ୍ଲଟ୍ ବୁକ୍ କରିନାହାଁନ୍ତି। ନୂଆ ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ।',
    bookNewSlot: '🌱 ନୂଆ ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ',
    quickActions: 'ତୁରନ୍ତ ସେବା',
    bookSlot: 'ସ୍ଲଟ୍ ବୁକିଂ',
    liveQueue: 'ଲାଇଭ୍ ଧାଡ଼ି',
    myPayments: 'ମୋର ପେମେଣ୍ଟ',
    govtSchemes: 'ସରକାରୀ ଯୋଜନା',
    mspRates: 'ଏମଏସପି ଦର (2026-27)',




  },

  as: {
    appName: 'কিষাণকিউ',
    tagline: 'স্মাৰ্ট মাণ্ডি। উচিত মূল্য। উজ্জ্বল ভৱিষ্যত।',
    farmersFirst: 'কৃষক প্ৰথম',
    brighterTomorrow: 'উজ্জ্বল ভৱিষ্যত',
    heroDesc: 'মাণ্ডি স্লট বুক কৰক, ফচল ট্ৰেক কৰক, উচিত মূল্য পাওক।',
    easyBooking: 'সহজ বুকিং',
    noQueues: 'দীঘলীয়া শাৰী নাই',
    fairPrices: 'উচিত মূল্য',
    transparentMSP: 'স্বচ্ছ এমএছপি',
    empowered: 'সশক্ত কৃষক',
    digitalHassleFree: 'ডিজিটেল আৰু সহজ',
    welcomeTo: 'স্বাগতম',
    signInGoogleDesc: 'আৰম্ভ কৰিবলৈ গুগল একাউণ্টেৰে চাইন ইন কৰক',
    continueWithGoogle: 'গুগলৰ সৈতে আগবাঢ়ক',
    instantDemoLogin: 'ততালিকে ডেমো লগইন (১-টেপ)',
    or: 'বা',
    securedBy: 'Google আৰু Firebase দ্বাৰা সুৰক্ষিত',
    transparent: 'স্বচ্ছ',
    getFairPricesMsp: 'এমএছপিৰ সৈতে\nউচিত মূল্য পাওক',
    bookMandiSlotsInMin: 'মিনিটতে মাণ্ডি\nস্লট বুক কৰক',
    digitalServicesEveryFarmer: 'প্ৰতিজন কৃষকৰ বাবে\nডিজিটেল সেৱা',
    termsAgreement: 'অব্যাহত ৰাখি, আপুনি সন্মতি জনায়',
    termsOfService: 'সেৱাৰ চৰ্তাৱলী',
    privacyPolicy: 'গোপনীয়তা নীতি',
    chooseLanguage: 'ভাষা বাছক',
    selectPreferredLang: 'আপোনাৰ পছন্দৰ ভাষা বাছক',
    skip: 'এৰাই চলক',
    next: 'পৰৱৰ্তী',
    getStarted: 'আৰম্ভ কৰক',
    onboarding1Title: 'শাৰীত নথিয়াকৈ মাণ্ডিত',
    onboarding1Highlight: 'স্লট বুক কৰক',
    onboarding1Desc: 'সময় বচাওক, সহজেই আপোনাৰ মাণ্ডি প্ৰৱেশ স্লট বুক কৰক।',
    onboarding2Title: 'ডিজিটেল ওজন,',
    onboarding2Highlight: 'সরাসৰি এমএছপি ধন',
    onboarding2Desc: 'সঠিক ওজন, পোনপটীয়াকৈ বেংক একাউণ্টত এমএছপিৰ ধন।',
    onboarding3Title: 'লাইভ শাৰী',
    onboarding3Highlight: 'ফোনতে লাইভ ট্ৰেকিং',
    onboarding3Desc: 'টোকেন স্থিতি আৰু সময় ফোনতে লাইভ চাওক।',
    onboarding4Title: 'চৰকাৰী আঁচনি আৰু',
    onboarding4Highlight: 'ডিজিলকাৰ কেৱাইচি',
    onboarding4Desc: 'সকলো চৰকাৰী কৃষি আঁচনি আৰু সহজ ডিজিটেল পৰীক্ষণ।',
    greetingNamaste: 'নমস্কাৰ',
    goodToSeeYou: 'আপোনাক পুনৰ দেখি ভাল লাগিল',
    makeFarmingRewarding: 'আহক কৃষিক আৰু অধিক লাভজনক কৰোঁ।',
    farmerSlogan: '🌾 কৃষকৰ শ্ৰম, দেশৰ শক্তি 🌾',
    activeBookings: 'সক্ৰিয় বুকিং',
    queuePosition: 'শাৰী স্থান',
    pendingPayments: 'বাকী থকা ধন',
    totalProcured: 'মুঠ ক্ৰয়',
    spotlightActive: 'সক্ৰিয় বুকিং',
    spotlightCompleted: 'ক্ৰয় সম্পূৰ্ণ',
    viewAll: 'সকলো চাওক ›',
    noActiveBookings: 'কোনো সক্ৰিয় বুকিং নাই',
    noActiveBookingsDesc: 'আপুনি এতিয়ালৈকে কোনো স্লট বুক কৰা নাই। নতুন স্লট বুক কৰক।',
    bookNewSlot: '🌱 নতুন স্লট বুক কৰক',
    quickActions: 'দ্ৰুত সেৱা',
    bookSlot: 'স্লট বুকিং',
    liveQueue: 'লাইভ শাৰী',
    myPayments: 'মোৰ ধন',
    govtSchemes: 'চৰকাৰী আঁচনি',
    mspRates: 'এমএছপি দৰ (2026-27)',




  },

  ur: {
    appName: 'کسان قطار',
    tagline: 'اسمارٹ منڈی۔ صحیح قیمت۔ بہتر مستقبل۔',
    farmersFirst: 'کسان پہلے',
    brighterTomorrow: 'روشن مستقبل',
    heroDesc: 'منڈی سلاٹ بک کریں، فصل ٹریک کریں، صحیح قیمت پائیں — سب ایک ایپ میں۔',
    easyBooking: 'آسان بکنگ',
    noQueues: 'لمبی قطاروں سے نجات',
    fairPrices: 'صحیح قیمت',
    transparentMSP: 'شفاف ایم ایس پی',
    empowered: 'بااختیار کسان',
    digitalHassleFree: 'ڈیجیٹل اور آسان',
    welcomeTo: 'خوش آمدید',
    signInGoogleDesc: 'شروع کرنے کے لیے اپنے گوگل اکاؤنٹ سے لاگ ان کریں',
    continueWithGoogle: 'گوگل کے ساتھ جاری رکھیں',
    instantDemoLogin: 'فوری ڈیمو لاگ ان (1-ٹیپ)',
    or: 'یا',
    securedBy: 'گوگل اور فائر بیس کے ذریعے محفوظ',
    transparent: 'شفاف',
    getFairPricesMsp: 'ایم ایس پی کے ساتھ\nصحیح قیمت پائیں',
    bookMandiSlotsInMin: 'منٹوں میں منڈی\nسلاٹ بک کریں',
    digitalServicesEveryFarmer: 'ہر کسان کے لیے\nڈیجیٹل خدمات',
    termsAgreement: 'جاری رکھ کر، آپ متفق ہیں',
    termsOfService: 'سروس کی شرائط',
    privacyPolicy: 'رازداری کی پالیسی',
    chooseLanguage: 'زبان منتخب کریں',
    selectPreferredLang: 'اپنی پسندیدہ زبان منتخب کریں',
    skip: 'چھوڑیں',
    next: 'اگلا',
    getStarted: 'شروع کریں',
    onboarding1Title: 'منڈی میں قطار کے بغیر',
    onboarding1Highlight: 'سلاٹ بک کریں',
    onboarding1Desc: 'اپنا وقت بچائیں، منڈی میں داخلے کا سلاٹ آسانی سے بک کریں۔',
    onboarding2Title: 'ڈیجیٹل وزن،',
    onboarding2Highlight: 'براہ راست ایم ایس پی ادائیگی',
    onboarding2Desc: 'درست وزن، براہ راست بینک اکاؤنٹ میں بغیر کٹوتی رقم۔',
    onboarding3Title: 'لائیو قطار',
    onboarding3Highlight: 'موبائل پر لائیو ٹریکنگ',
    onboarding3Desc: 'اپنا ٹوکن نمبر اور وقت موبائل پر لائیو دیکھیں۔',
    onboarding4Title: 'سرکاری اسکیمیں اور',
    onboarding4Highlight: 'ڈیجی لاکر کے وائی سی',
    onboarding4Desc: 'تمام زرعی اسکیموں کی معلومات اور آسان ڈیجیٹل تصدیق۔',
    greetingNamaste: 'آداب',
    goodToSeeYou: 'آپ کو دوبارہ دیکھ کر خوشی ہوئی',
    makeFarmingRewarding: 'آئیے آج کاشتکاری کو مزید منافع بخش بنائیں۔',
    farmerSlogan: '🌾 کسان کی محنت، ملک کی طاقت 🌾',
    activeBookings: 'فعال بکنگز',
    queuePosition: 'قطار کا نمبر',
    pendingPayments: 'بقایا رقم',
    totalProcured: 'کل خریداری',
    spotlightActive: 'فعال بکنگ',
    spotlightCompleted: 'خریداری مکمل',
    viewAll: 'تمام دیکھیں ›',
    noActiveBookings: 'کوئی فعال بکنگ نہیں',
    noActiveBookingsDesc: 'آپ نے ابھی تک کوئی منڈی سلاٹ بک نہیں کیا۔ فصل فروخت کے لیے نیا سلاٹ بک کریں۔',
    bookNewSlot: '🌱 نیا سلاٹ بک کریں',
    quickActions: 'فوری خدمات',
    bookSlot: 'سلاٹ بکنگ',
    liveQueue: 'لائیو قطار',
    myPayments: 'ادائیگی کی تفصیلات',
    govtSchemes: 'سرکاری اسکیمیں',
    mspRates: 'ایم ایس پی ریٹس (2026-27)',




  },

  bho: {
    appName: 'किसानकतार',
    tagline: 'स्मार्ट मंडी। सही दाम। सुंदर कल।',
    farmersFirst: 'किसान भाई सबसे पहिले',
    brighterTomorrow: 'सुखद कल',
    heroDesc: 'मंडी के स्लॉट बुक करीं, आपन फसल ट्रैक करीं, सही दाम पाईं — सभे एक्के ऐप में।',
    easyBooking: 'आसान बुकिंग',
    noQueues: 'लंबी लाइन से छुटकारा',
    fairPrices: 'सही दाम',
    transparentMSP: 'पारदर्शी एमएसपी',
    empowered: 'सशक्त किसान',
    digitalHassleFree: 'डिजिटल आ बिना झंझट',
    welcomeTo: 'राउर स्वागत बा',
    signInGoogleDesc: 'शुरू करे खातिर आपन गूगल एकाउंट से साइन इन करीं',
    continueWithGoogle: 'गूगल से आगे बढ़ीं',
    instantDemoLogin: 'तुरंत डेमो लॉगिन (1-टैप)',
    or: 'चाहे',
    securedBy: 'Google आ Firebase से सुरक्षित',
    transparent: 'पारदर्शी',
    getFairPricesMsp: 'एमएसपी के साथ\nसही दाम पाईं',
    bookMandiSlotsInMin: 'मिनट में मंडी\nस्लॉट बुक करीं',
    digitalServicesEveryFarmer: 'हर किसान खातिर\nडिजिटल सेवा',
    termsAgreement: 'आगे बढ़ के, रउआ सहमत बानी',
    termsOfService: 'सेवा के शर्त',
    privacyPolicy: 'गोपनीयता नीति',
    chooseLanguage: 'भाषा चुनीं',
    selectPreferredLang: 'आपन पसंद के भाषा चुनीं',
    skip: 'छोड़ीं',
    next: 'आगे',
    getStarted: 'शुरू करीं',
    onboarding1Title: 'मंडी में बिना लाइन में लगले',
    onboarding1Highlight: 'स्लॉट बुक करीं',
    onboarding1Desc: 'आपन समय बचाईं, आसानी से मंडी टोकन स्लॉट बुक करीं।',
    onboarding2Title: 'डिजिटल तौल,',
    onboarding2Highlight: 'सीधे खाता में एमएसपी',
    onboarding2Desc: 'सही तौल, बिना कवनो कटौती सीधे बैंक खाता में पइसा।',
    onboarding3Title: 'लाइव कतार',
    onboarding3Highlight: 'फोन पर लाइव ट्रैकिंग',
    onboarding3Desc: 'आपन टोकन नंबर आ समय लाइव देखीं, भीड़-भाड़ से बचीं।',
    onboarding4Title: 'सरकारी योजना आ',
    onboarding4Highlight: 'डिजीलॉकर केवाईसी',
    onboarding4Desc: 'सभ सरकारी योजना के जानकारी आ आसान डिजिटल सत्यापन।',
    greetingNamaste: 'प्रणाम',
    goodToSeeYou: 'रउआ से भेंट होके बहुत खुशी भइल',
    makeFarmingRewarding: 'आईं आज खेती के अउरी फायदेमंद बनावल जाव।',
    farmerSlogan: '🌾 किसान के मेहनत, देश के ताकत 🌾',
    activeBookings: 'चालू बुकिंग',
    queuePosition: 'लाइन में नंबर',
    pendingPayments: 'बाकी पइसा',
    totalProcured: 'कुल तौलल अनाज',
    spotlightActive: 'चालू बुकिंग',
    spotlightCompleted: 'तौल पूरा भइल',
    viewAll: 'सभे देखीं ›',
    noActiveBookings: 'कवनो बुकिंग नइखे',
    noActiveBookingsDesc: 'रउआ अभिन कवनो मंडी स्लॉट बुक नइखीं कइले। नया स्लॉट बुक करीं।',
    bookNewSlot: '🌱 नया स्लॉट बुक करीं',
    quickActions: 'झटपट सेवा',
    bookSlot: 'स्लॉट बुक करीं',
    liveQueue: 'लाइव कतार',
    myPayments: 'भुगतान ब्योरा',
    govtSchemes: 'सरकारी योजना',
    mspRates: 'एमएसपी रेट (2026-27)',




  },

  mai: {
    appName: 'किसानकतार',
    tagline: 'स्मार्ट मंडी। उचित दर। नवका बिहान।',
    farmersFirst: 'किसान सर्वोपरि',
    brighterTomorrow: 'सुखद भविष्य',
    heroDesc: 'मंडी स्लॉट बुक करू, फसल ट्रैक करू, उचित मूल्य पाबू — सब एक्के ऐप मे।',
    easyBooking: 'सहज बुकिंग',
    noQueues: 'कतार सँ मुक्ति',
    fairPrices: 'उचित दर',
    transparentMSP: 'पारदर्शी एमएसपी',
    empowered: 'सशक्त किसान',
    digitalHassleFree: 'डिजिटल आ सहज',
    welcomeTo: 'स्वागत अछि',
    signInGoogleDesc: 'शुरू करबाक लेल गूगल अकाउंट सँ साइन इन करू',
    continueWithGoogle: 'गूगल संग आगू बढ़ू',
    instantDemoLogin: 'झटपट डेमो लॉगिन (1-टैप)',
    or: 'अथवा',
    securedBy: 'Google आ Firebase द्वारा सुरक्षित',
    transparent: 'पारदर्शी',
    getFairPricesMsp: 'एमएसपी संग\nउचित दर पाबू',
    bookMandiSlotsInMin: 'मिनट मे मंडी\nस्लॉट बुक करू',
    digitalServicesEveryFarmer: 'हरेक किसान लेल\nडिजिटल सेवा',
    termsAgreement: 'आगू बढ़ि कए, अहाँ सहमत छी',
    termsOfService: 'सेवाक शर्त',
    privacyPolicy: 'गोपनीयता नीति',
    chooseLanguage: 'भाषा चुनू',
    selectPreferredLang: 'आपन मनपसंद भाषा चुनू',
    skip: 'छोड़ू',
    next: 'आगू',
    getStarted: 'आरंभ करू',
    onboarding1Title: 'मंडी मे बिना लाइन लगौने',
    onboarding1Highlight: 'स्लॉट बुक करू',
    onboarding1Desc: 'समय बचाउ, सहजता सँ अपन मंडी प्रवेश स्लॉट बुक करू।',
    onboarding2Title: 'डिजिटल तौल,',
    onboarding2Highlight: 'सीधे खाता मे एमएसपी',
    onboarding2Desc: 'सटीक वजन, बिना कटौती बैंक खाता मे पूरा एमएसपी राशि।',
    onboarding3Title: 'लाइव कतार',
    onboarding3Highlight: 'मोबाइल पर लाइव ट्रैकिंग',
    onboarding3Desc: 'टोकन संख्या आ अनुमानित समय लाइव देखू, भीड़ सँ बचू।',
    onboarding4Title: 'सरकारी योजना आ',
    onboarding4Highlight: 'डिजीलॉकर केवाईसी',
    onboarding4Desc: 'सब सरकारी कृषि योजनाक जानकारी आ आसान सत्यापन।',
    greetingNamaste: 'प्रणाम',
    goodToSeeYou: 'अहाँ सँ भेट कऽ अति प्रसन्नता भेल',
    makeFarmingRewarding: 'आउ आजुक दिन खेती केँ आओर लाभकारी बनाबी।',
    farmerSlogan: '🌾 किसानक पसीना, देशक प्रतिष्ठा 🌾',
    activeBookings: 'सक्रिय बुकिंग',
    queuePosition: 'कतार क्रमांक',
    pendingPayments: 'बकाया राशि',
    totalProcured: 'कुल खरीद',
    spotlightActive: 'सक्रिय बुकिंग',
    spotlightCompleted: 'खरीद संपन्न',
    viewAll: 'सब देखू ›',
    noActiveBookings: 'कोनो सक्रिय बुकिंग नहि',
    noActiveBookingsDesc: 'अहाँ अखन धरि कोनो स्लॉट बुक नहि कएने छी। नव स्लॉट बुक करू।',
    bookNewSlot: '🌱 नव स्लॉट बुक करू',
    quickActions: 'त्वरित सेवा',
    bookSlot: 'स्लॉट बुक',
    liveQueue: 'लाइव कतार',
    myPayments: 'भुगतान विवरण',
    govtSchemes: 'सरकारी योजना',
    mspRates: 'एमएसपी दर (2026-27)',




  },

  sa: {
    appName: 'कृषकपङ्क्तिः',
    tagline: 'विपणनम्। उचितमूल्यम्। समृद्धं भविष्यम्।',
    farmersFirst: 'कृषकः प्रथमः',
    brighterTomorrow: 'उज्ज्वलं भविष्यम्',
    heroDesc: 'विपणि-प्रवेशं निर्धारयत, उत्पादनं पश्यत, उचितं मूल्यं प्राप्नुवत।',
    easyBooking: 'सरला पञ्जीकरणम्',
    noQueues: 'दीर्घपङ्क्ति-मुक्तिः',
    fairPrices: 'उचितं मूल्यम्',
    transparentMSP: 'पारदर्शि न्यूनतमसमर्थनमूल्यम्',
    empowered: 'सशक्तः कृषकः',
    digitalHassleFree: 'डिजिटल तथा सरलम्',
    welcomeTo: 'स्वागतम्',
    signInGoogleDesc: 'आरम्भाय गूगल-खातेन प्रवेशं कुर्वन्तु',
    continueWithGoogle: 'गूगल-माध्यमेन अग्रे सरन्तु',
    instantDemoLogin: 'झटिति डेमो-प्रवेशः (एकस्पर्शः)',
    or: 'अथवा',
    securedBy: 'Google तथा Firebase द्वारा सुरक्षितम्',
    transparent: 'पारदर्शकता',
    getFairPricesMsp: 'एमएसपी सह\nउचितं मूल्यं प्राप्नुवत',
    bookMandiSlotsInMin: 'निमेषेषु विपणि\nस्थानं निर्धारयत',
    digitalServicesEveryFarmer: 'प्रति कृषकं प्रति\nडिजिटल-सेवा',
    termsAgreement: 'अग्रे गत्वा, भवन्तः स्वीकुर्वन्ति',
    termsOfService: 'सेवा-नियमाः',
    privacyPolicy: 'गोपनीयता-नीतिः',
    chooseLanguage: 'भाषां चिनुत',
    selectPreferredLang: 'स्वाभीष्ट-भाषां चिनुत',
    skip: 'त्यजतु',
    next: 'अग्रिमम्',
    getStarted: 'आरभताम्',
    onboarding1Title: 'विपणौ पङ्क्तौ अतिष्ठन्तः',
    onboarding1Highlight: 'स्थानं निर्धारयत',
    onboarding1Desc: 'समयस्य संरक्षणं कुर्वन्तु, सुखेन विपणि-प्रवेशस्थानं निर्धारयत।',
    onboarding2Title: 'डिजिटल-तोलनम्,',
    onboarding2Highlight: 'प्रत्यक्षं एमएसपी धनम्',
    onboarding2Desc: 'सटीकं तोलनम्, साक्षात् वित्तकोष-खातायां संपूर्णं धनम्।',
    onboarding3Title: 'प्रत्यक्ष-पङ्क्तिः',
    onboarding3Highlight: 'चलदूरभाषे प्रत्यक्ष-दर्शनम्',
    onboarding3Desc: 'पङ्क्ति-स्थानं समयं च चलदूरभाषे पश्यन्तु।',
    onboarding4Title: 'सर्वकार-योजनाः तथा',
    onboarding4Highlight: 'डिजीलॉकर-केवाईसी',
    onboarding4Desc: 'सर्वकार-योजनानां ज्ञानं तथा सरलं डिजिटल-प्रमाणीकरणम्।',
    greetingNamaste: 'नमस्ते',
    goodToSeeYou: 'भवन्तं दृष्ट्वा अतीव आनन्दः',
    makeFarmingRewarding: 'अद्य कृषिं समृद्धितरां करवाम।',
    farmerSlogan: '🌾 कृषकस्य परिश्रमः, राष्ट्रस्य सामर्थ्यम् 🌾',
    activeBookings: 'सक्रियांशाः',
    queuePosition: 'पङ्क्तिस्थानम्',
    pendingPayments: 'अवशिष्टं देयम्',
    totalProcured: 'कुलक्रयणम्',
    spotlightActive: 'सक्रियस्थानम्',
    spotlightCompleted: 'क्रयणं सम्पन्नम्',
    viewAll: 'सर्वं पश्यन्तु ›',
    noActiveBookings: 'कोऽपि सक्रिया पञ्जीकरणं नास्ति',
    noActiveBookingsDesc: 'भवद्भिः अद्यापि विपणिस्थानं न निर्धारितम्। नूतनं स्थानं निर्धारयत।',
    bookNewSlot: '🌱 नूतनं स्थानं निर्धारयत',
    quickActions: 'शीघ्रसेवाः',
    bookSlot: 'स्थाननिर्धारणम्',
    liveQueue: 'प्रत्यक्षपङ्क्तिः',
    myPayments: 'मम देयानि',
    govtSchemes: 'शासकीययोजनाः',
    mspRates: 'न्यूनतमसमर्थनमूल्यम् (2026-27)',




  },

  kok: {
    appName: 'किसानरांक',
    tagline: 'स्मार्ट मार्केट. बरो भाव. फुडार बरो.',
    farmersFirst: 'शेतकार पयलीं',
    brighterTomorrow: 'बरो फुडार',
    heroDesc: 'मार्केट स्लॉट बुक करात, पीक ट्रॅक करात, बरो भाव मेळयात.',
    easyBooking: 'सोपें बुकिंग',
    noQueues: 'लांब रांक ना',
    fairPrices: 'योग्य दर',
    transparentMSP: 'पारदर्शक हमीभाव',
    empowered: 'सशक्त शेतकार',
    digitalHassleFree: 'डिजिटल आनी सोंपें',
    welcomeTo: 'येवकार',
    signInGoogleDesc: 'सुरू करपाक गुगल खात्यान सायन इन करात',
    continueWithGoogle: 'Google वांगडा मुखार वचात',
    instantDemoLogin: 'रोकडेंच डेमो लॉगिन (1-टॅप)',
    or: 'ना जाल्यार',
    securedBy: 'Google आनी Firebase वरवीं सुरक्षित',
    transparent: 'पारदर्शक',
    getFairPricesMsp: 'हमीभावा वांगडा\nयोग्य दर मेळयात',
    bookMandiSlotsInMin: 'मिनिटांनी मार्केट\nस्लॉट बुक करात',
    digitalServicesEveryFarmer: 'दर एका शेतकारा खातीर\nडिजिटल सेवा',
    termsAgreement: 'मुखार वचून, तुमी मान्य करतात',
    termsOfService: 'सेवा अटी',
    privacyPolicy: 'गोपनीयता धोरण',
    chooseLanguage: 'भास वेचात',
    selectPreferredLang: 'तुमची आवडीची भास वेचात',
    skip: 'सोडात',
    next: 'मुखार',
    getStarted: 'सुरू करात',
    onboarding1Title: 'मार्केटांत रांकेत राविनासताना',
    onboarding1Highlight: 'स्लॉट बुक करात',
    onboarding1Desc: 'वेळ वांचयात, सोपेपणान तुमचो मार्केट स्लॉट बुक करात.',
    onboarding2Title: 'डिजिटल वजन,',
    onboarding2Highlight: 'थेट हमीभाव पेमेंट',
    onboarding2Desc: 'सारकें वजन, थेट तुमच्या बँक खात्यांत हमीभावाचे पयशे.',
    onboarding3Title: 'थेट रांक',
    onboarding3Highlight: 'मोबायलाचेर थेट ट्रॅकिंग',
    onboarding3Desc: 'टोकन नंबर आनी वेळ मोबायलाचेर थेट पळयात, गर्दी टाळात.',
    onboarding4Title: 'सरकारी येवजण्यो आनी',
    onboarding4Highlight: 'डिजिलॉकर केवायसी',
    onboarding4Desc: 'सरकारी शेतकी येवजण्यांची म्हायती आनी सोंपी डिजिटल तपासणी.',
    greetingNamaste: 'नमस्कार',
    goodToSeeYou: 'परतून मेळून खोशी जाली',
    makeFarmingRewarding: 'चलात शेती आनीक फायद्याची करूंया.',
    farmerSlogan: '🌾 शेतकाराचो घाम, देशाची शक्त 🌾',
    activeBookings: 'सक्रिय बुकिंगां',
    queuePosition: 'रांकेतलो नंबर',
    pendingPayments: 'उरिल्ली रक्कम',
    totalProcured: 'एकूण खरेदी',
    spotlightActive: 'सक्रिय बुकिंग',
    spotlightCompleted: 'खरेदी पुराय जाली',
    viewAll: 'सगळें पळयात ›',
    noActiveBookings: 'सक्रिय बुकिंग ना',
    noActiveBookingsDesc: 'तुमी अजून स्लॉट बुक करूंक ना. नवो स्लॉट बुक करात.',
    bookNewSlot: '🌱 नवो स्लॉट बुक करात',
    quickActions: 'रोखड्यो सेवा',
    bookSlot: 'स्लॉट बुकिंग',
    liveQueue: 'थेट रांक',
    myPayments: 'म्हाका मेळिल्ले पयशे',
    govtSchemes: 'सरकारी येवजण्यो',
    mspRates: 'हमीभाव दर (2026-27)',




  },

  sd: {
    appName: 'ڪسان قطار',
    tagline: 'سمارٽ منڊي. صحيح اگهه. روشن سڀاڻي.',
    farmersFirst: 'هارِي پهريان',
    brighterTomorrow: 'روشن مستقبل',
    heroDesc: 'منڊي سلاٽ بڪ ڪريو، فصل ٽريڪ ڪريو، صحيح اگهه حاصل ڪريو.',
    easyBooking: 'سولو بڪنگ',
    noQueues: 'ڊگهين قطارن کان نجات',
    fairPrices: 'صحيح اگهه',
    transparentMSP: 'شفاف ايم ايس پي',
    empowered: 'بااختيار هاري',
    digitalHassleFree: 'ڊيجيٽل ۽ آسان',
    welcomeTo: 'ڀلي ڪري آيا',
    signInGoogleDesc: 'شروع ڪرڻ لاءِ پنهنجي گوگل کاتي سان لاگ ان ٿيو',
    continueWithGoogle: 'گوگل سان اڳتي وڌو',
    instantDemoLogin: 'فوري ڊيمو لاگ ان (1-ٽيپ)',
    or: 'يا',
    securedBy: 'Google ۽ Firebase سان محفوظ',
    transparent: 'شفاف',
    getFairPricesMsp: 'ايم ايس پي سان\nصحيح اگهه ماڻيو',
    bookMandiSlotsInMin: 'منٽن ۾ منڊي\nسلاٽ بڪ ڪريو',
    digitalServicesEveryFarmer: 'هر هاريءَ لاءِ\nڊيجيٽل سهولتون',
    termsAgreement: 'اڳتي وڌڻ سان، توهان متفق آهيو',
    termsOfService: 'خدمت جا شرط',
    privacyPolicy: 'رازداري پاليسي',
    chooseLanguage: 'ٻولي چونڊيو',
    selectPreferredLang: 'پنهنجي پسند جي ٻولي چونڊيو',
    skip: 'ڇڏي ڏيو',
    next: 'اڳيون',
    getStarted: 'شروع ڪريو',
    onboarding1Title: 'منڊيءَ ۾ قطار کان سواءِ',
    onboarding1Highlight: 'سلاٽ بڪ ڪريو',
    onboarding1Desc: 'وقت بچايو، آسانيءَ سان پنهنجو منڊي انٽري سلاٽ بڪ ڪريو.',
    onboarding2Title: 'ڊيجيٽل تور،',
    onboarding2Highlight: 'سڌي ايم ايس پي رقم',
    onboarding2Desc: 'صحيح تور، بغير ڪنهن ڪٽوتي جي سڌو بئنڪ کاتي ۾ پئسا.',
    onboarding3Title: 'لائيو قطار',
    onboarding3Highlight: 'موبائل تي لائيو ٽريڪنگ',
    onboarding3Desc: 'ٽوڪن نمبر ۽ اندازي وارو وقت موبائل تي لائيو ڏسو.',
    onboarding4Title: 'سرڪاري اسڪيمون ۽',
    onboarding4Highlight: 'ڊيجي لاڪر تصديق',
    onboarding4Desc: 'سمورين زرعي اسڪيمن جي ڄاڻ ۽ آسان ڊيجيٽل چڪاس.',
    greetingNamaste: 'سلام',
    goodToSeeYou: 'توهان کي وري ڏسي خوشي ٿي',
    makeFarmingRewarding: 'اچو ته زراعت کي وڌيڪ فائديمند بڻايون.',
    farmerSlogan: '🌾 هاريءَ جو پگهر، ملڪ جو فخر 🌾',
    activeBookings: 'فعال بڪنگ',
    queuePosition: 'قطار ۾ نمبر',
    pendingPayments: 'رهيل رقم',
    totalProcured: 'ڪل خريداري',
    spotlightActive: 'فعال بڪنگ',
    spotlightCompleted: 'خريداري مڪمل',
    viewAll: 'سڀ ڏسو ›',
    noActiveBookings: 'ڪابه فعال بڪنگ ناهي',
    noActiveBookingsDesc: 'توهان اڃا تائين ڪو به سلاٽ بڪ ناهي ڪيو. نئون سلاٽ بڪ ڪريو.',
    bookNewSlot: '🌱 نئون سلاٽ بڪ ڪريو',
    quickActions: 'تيز خدمتون',
    bookSlot: 'سلاٽ بڪنگ',
    liveQueue: 'لائيو قطار',
    myPayments: 'پئسن جا تفصيل',
    govtSchemes: 'سرڪاري اسڪيمون',
    mspRates: 'ايم ايس پي ريٽ (2026-27)',




  },

  ne: {
    appName: 'किसानकतार',
    tagline: 'स्मार्ट मण्डी। उचित मूल्य। उज्यालो भोलि।',
    farmersFirst: 'किसान पहिलो',
    brighterTomorrow: 'उज्यालो भविष्य',
    heroDesc: 'मण्डी स्लट बुक गर्नुहोस्, बाली ट्र्याक गर्नुहोस्, उचित मूल्य पाउनुहोस्।',
    easyBooking: 'सजिलो बुकिङ',
    noQueues: 'लामो लाइनबाट मुक्ति',
    fairPrices: 'उचित मूल्य',
    transparentMSP: 'पारदर्शी समर्थन मूल्य',
    empowered: 'सशक्त किसान',
    digitalHassleFree: 'डिजिटल र झन्झटमुक्त',
    welcomeTo: 'स्वागत छ',
    signInGoogleDesc: 'सुरु गर्न आफ्नो गुगल खाताबाट साइन इन गर्नुहोस्',
    continueWithGoogle: 'गुगलसँग अगाडि बढ्नुहोस्',
    instantDemoLogin: 'तुरुन्तै डेमो लगइन (१-ट्याप)',
    or: 'वा',
    securedBy: 'Google र Firebase द्वारा सुरक्षित',
    transparent: 'पारदर्शी',
    getFairPricesMsp: 'समर्थन मूल्यसँग\nउचित दर पाउनुहोस्',
    bookMandiSlotsInMin: 'मिनेटमै मण्डी\nस्लट बुक गर्नुहोस्',
    digitalServicesEveryFarmer: 'हरेक किसानका लागि\nडिजिटल सेवा',
    termsAgreement: 'जारी राखेर, तपाईं सहमत हुनुहुन्छ',
    termsOfService: 'सेवाका सर्तहरू',
    privacyPolicy: 'गोपनीयता नीति',
    chooseLanguage: 'भाषा छान्नुहोस्',
    selectPreferredLang: 'आफ्नो मनपर्ने भाषा छान्नुहोस्',
    skip: 'छोड्नुहोस्',
    next: 'अर्को',
    getStarted: 'सुरु गर्नुहोस्',
    onboarding1Title: 'मण्डीमा लाइन नबसी',
    onboarding1Highlight: 'स्लट बुक गर्नुहोस्',
    onboarding1Desc: 'समय बचाउनुहोस्, सजिलै आफ्नो मण्डी प्रवेश स्लट बुक गर्नुहोस्।',
    onboarding2Title: 'डिजिटल तौल,',
    onboarding2Highlight: 'सोझै खातामा भुक्तानी',
    onboarding2Desc: 'सटीक तौल, सिधै आफ्नो बैंक खातामा समर्थन मूल्यको भुक्तानी।',
    onboarding3Title: 'प्रत्यक्ष कतार',
    onboarding3Highlight: 'मोबाइलमा प्रत्यक्ष ट्र्याकिङ',
    onboarding3Desc: 'टोकन नम्बर र अनुमानित समय मोबाइलमै प्रत्यक्ष हेर्नुहोस्।',
    onboarding4Title: 'सरकारी योजना र',
    onboarding4Highlight: 'डिजिलकर केवाइसी',
    onboarding4Desc: 'सबै सरकारी कृषि योजनाको जानकारी र सजिलो डिजिटल प्रमाणीकरण।',
    greetingNamaste: 'नमस्ते',
    goodToSeeYou: 'तपाईंलाई फेरि भेट्दा खुसी लाग्यो',
    makeFarmingRewarding: 'आउनुहोस् आज खेतीलाई अझ बढी लाभदायक बनाऔं।',
    farmerSlogan: '🌾 किसानको पसिना, देशको शक्ति 🌾',
    activeBookings: 'सक्रिय बुकिङहरू',
    queuePosition: 'लाइन नम्बर',
    pendingPayments: 'बाँकी भुक्तानी',
    totalProcured: 'कुल खरिद',
    spotlightActive: 'सक्रिय बुकिङ',
    spotlightCompleted: 'खरिद सम्पन्न',
    viewAll: 'सबै हेर्नुहोस् ›',
    noActiveBookings: 'कुनै सक्रिय बुकिङ छैन',
    noActiveBookingsDesc: 'तपाईंले अहिलेसम्म कुनै स्लट बुक गर्नुभएको छैन। नयाँ स्लट बुक गर्नुहोस्।',
    bookNewSlot: '🌱 नयाँ स्लट बुक गर्नुहोस्',
    quickActions: 'द्रुत सेवाहरू',
    bookSlot: 'स्लट बुकिङ',
    liveQueue: 'प्रत्यक्ष कतार',
    myPayments: 'मेरो भुक्तानी',
    govtSchemes: 'सरकारी योजनाहरू',
    mspRates: 'समर्थन मूल्य (2026-27)',




  },

  doi: {
    appName: 'किसानकतार',
    tagline: 'स्मार्ट मंडी। सही मुल्ल। सुनहरी कल्ल।',
    farmersFirst: 'किसान पैहले',
    brighterTomorrow: 'सुनहरी कल्ल',
    heroDesc: 'मंडी स्लॉट बुक करो, जिन्स ट्रैक करो, सही मुल्ल पाओ — सब इक ऐप च।',
    easyBooking: 'सौखी बुकिंग',
    noQueues: 'लम्मियां लाईनां नेईं',
    fairPrices: 'सही मुल्ल',
    transparentMSP: 'पारदर्शी एमएसपी',
    empowered: 'सशक्त किसान',
    digitalHassleFree: 'डिजिटल ते सौखा',
    welcomeTo: 'जी आयां नूं',
    signInGoogleDesc: 'शुरू करने लेई गूगल खाते कन्ने साइन इन करो',
    continueWithGoogle: 'गूगल कन्ने अग्गें बधो',
    instantDemoLogin: 'झटपट डेमो लॉगिन (1-टैप)',
    or: 'या',
    securedBy: 'Google ते Firebase कन्ने सुरक्षित',
    transparent: 'पारदर्शी',
    getFairPricesMsp: 'एमएसपी कन्ने\nसही मुल्ल पाओ',
    bookMandiSlotsInMin: 'मिनटां च मंडी\nस्लॉट बुक करो',
    digitalServicesEveryFarmer: 'हर किसान लेई\nडिजिटल सेवा',
    termsAgreement: 'जारी रक्खी तैं, तुस सहमत ओ',
    termsOfService: 'सेवा दी शर्त',
    privacyPolicy: 'गोपनीयता नीति',
    chooseLanguage: 'बोली चुनो',
    selectPreferredLang: 'अपनी मनपसंद बोली चुनो',
    skip: 'छोडो',
    next: 'अग्गें',
    getStarted: 'शुरू करो',
    onboarding1Title: 'मंडी च बिना लाइन लग्गे',
    onboarding1Highlight: 'स्लॉट बुक करो',
    onboarding1Desc: 'समां बचाओ, सौखे ढंगै कन्ने मंडी स्लॉट बुक करो।',
    onboarding2Title: 'डिजिटल तोल,',
    onboarding2Highlight: 'सीधा एमएसपी भुगतान',
    onboarding2Desc: 'सही तोल, बिना किश कट्टै सीधा बैंक खाते च पैसा।',
    onboarding3Title: 'लाइव कतार',
    onboarding3Highlight: 'फोन उप्पर लाइव ट्रैकिंग',
    onboarding3Desc: 'टोकन नंबर ते समां फोन उप्पर लाइव दिक्खो।',
    onboarding4Title: 'सरकारी योजना ते',
    onboarding4Highlight: 'डिजीलॉकर केवाईसी',
    onboarding4Desc: 'सारियां सरकारी स्कीमां दी जानकारी ते सौखी जांच।',
    greetingNamaste: 'नमस्ते',
    goodToSeeYou: 'तुसेंगी दिक्खी तैं बड़ी खुशी होई',
    makeFarmingRewarding: 'आओ खेती गी होर फायदेमंद बनाइये।',
    farmerSlogan: '🌾 किसान दी मिहनत, मुल्क दी ताकत 🌾',
    activeBookings: 'चालू बुकिंगां',
    queuePosition: 'लाइन च नंबर',
    pendingPayments: 'बकाया पैसा',
    totalProcured: 'कुल तोल',
    spotlightActive: 'चालू बुकिंग',
    spotlightCompleted: 'खरीद पूरी होई',
    viewAll: 'सब दिक्खो ›',
    noActiveBookings: 'कोई चालू बुकिंग नेईं',
    noActiveBookingsDesc: 'तुस अजें कोई स्लॉट बुक नेईं कीता। नया स्लॉट बुक करो।',
    bookNewSlot: '🌱 नया स्लॉट बुक करो',
    quickActions: 'झटपट सेवा',
    bookSlot: 'स्लॉट बुक',
    liveQueue: 'लाइव कतार',
    myPayments: 'भुगतान ब्योरा',
    govtSchemes: 'सरकारी स्कीमां',
    mspRates: 'एमएसपी दर (2026-27)',




  },

  ks: {
    appName: 'کسان قطار',
    tagline: 'سمارٹ منڈی۔ صحیح قیمت۔ روشن صبا۔',
    farmersFirst: 'زمیندار گۄڈٕ',
    brighterTomorrow: 'روشن مستقبل',
    heroDesc: 'منڈی سلاٹ کٔریو بُک، فصل کٔریو ٹریک، حلال تہٕ صحیح قیمت لٔبیو۔',
    easyBooking: 'سَہل بُکنگ',
    noQueues: 'زیٹھین قطارن نِش نجات',
    fairPrices: 'صحیح قیمت',
    transparentMSP: 'صاف ایم ایس پی',
    empowered: 'مضبوط زمیندار',
    digitalHassleFree: 'ڈیجیٹل تہٕ آسان',
    welcomeTo: 'خوش آمدید',
    signInGoogleDesc: 'شروع کرنہٕ خٲطرٕ کٔریو گوگل اکاؤنٹ سٕتۍ لاگ اِن',
    continueWithGoogle: 'گوگل سٕتۍ برونہہ پکیو',
    instantDemoLogin: 'فوری ڈیمو لاگ اِن (1-ٹَیپ)',
    or: 'یا',
    securedBy: 'Google تہٕ Firebase سٕتۍ محفوظ',
    transparent: 'صاف تہٕ شفاف',
    getFairPricesMsp: 'ایم ایس پی سٕتۍ\nصحیح قٟمَتھ لٔبیو',
    bookMandiSlotsInMin: 'منٹن منٛز کٔریو منڈی\nسلاٹ بُک',
    digitalServicesEveryFarmer: 'پرٛتھ اکھ زمیندار خٲطرٕ\nڈیجیٹل خِدمت',
    termsAgreement: 'برونٛہہ پکنہٕ سٕتۍ چھِ تُہۍ متفق',
    termsOfService: 'خدمت کؠ شرائط',
    privacyPolicy: 'پرائیویسی پالیسی',
    chooseLanguage: 'زبان کٔریو منتخب',
    selectPreferredLang: 'پَنٕنۍ پسندیدہ زبان چُنیو',
    skip: 'تَرک کٔریو',
    next: 'برونٛہہ',
    getStarted: 'شۆروٗع کٔریو',
    onboarding1Title: 'منڈی منٛز لائنہِ بغٲر',
    onboarding1Highlight: 'سلاٹ کٔریو بُک',
    onboarding1Desc: 'وقت بچٲویو، سَہل طریقہٕ کٔریو منڈی انٹری سلاٹ بُک۔',
    onboarding2Title: 'ڈیجیٹل وَزَن،',
    onboarding2Highlight: 'سیدھا ایم ایس پی ادائیگی',
    onboarding2Desc: 'سچی وزنداری، بغیر کہنہِ کٹوتی سیدھے بینک کھاتس منٛز رقم۔',
    onboarding3Title: 'لائیو قطار',
    onboarding3Highlight: 'موبائلس پؠٹھ لائیو ٹریکنگ',
    onboarding3Desc: 'ٹوکن نمبر تہٕ وقت وُچھیو موبائلس پؠٹھ لائیو۔',
    onboarding4Title: 'سرکٲرۍ سکیٖم تہٕ',
    onboarding4Highlight: 'ڈیجی لاکر تصدیق',
    onboarding4Desc: 'تمام زراعتی سکیٖمن ہٕنٛز معلوٗمات تہٕ آسان ڈیجیٹل جانچ۔',
    greetingNamaste: 'سلام',
    goodToSeeYou: 'تۄہہِ پؠٹھ بیٚیہِ گۆم خوش',
    makeFarmingRewarding: 'أسی بنٲوو زمینداری ہور فایدہ مند۔',
    farmerSlogan: '🌾 زمیندار سُنٛد پسینہٕ، قۆمُک طاقت 🌾',
    activeBookings: 'چالو بُکنگ',
    queuePosition: 'قطار نمبر',
    pendingPayments: 'روپیہِ بقایا',
    totalProcured: 'کُل خریداری',
    spotlightActive: 'چالو بُکنگ',
    spotlightCompleted: 'خریداری مکمل',
    viewAll: 'سٲری وُچھیو ›',
    noActiveBookings: 'کانٛہہ چالو بُکنگ چِھنہٕ',
    noActiveBookingsDesc: 'تۄہیہِ چھُنہٕ وُنہِ کانٛہہ سلاٹ بُک کۄرمُت۔ نوٚو سلاٹ کٔریو بُک۔',
    bookNewSlot: '🌱 نوٚو سلاٹ کٔریو بُک',
    quickActions: 'فوری خدمات',
    bookSlot: 'سلاٹ بُکنگ',
    liveQueue: 'لائیو قطار',
    myPayments: 'پونسن ہٕنٛد تفصیٖل',
    govtSchemes: 'سرکٲرۍ سکیٖمہٕ',
    mspRates: 'ایم ایس پی ریٹ (2026-27)',




  },

  'mni-Mtei': {
    appName: 'কিসানক্বিউ',
    tagline: 'স্মার্ট মান্দি। অচুম্বা মমল। ফজরবা তুংলমচৎ।',
    farmersFirst: 'লৌমি হান্না',
    brighterTomorrow: 'ফজরবা তুংলমচৎ',
    heroDesc: 'মান্দি স্লট বুক তৌবিয়ু, পোত্থোক য়েংশিনবিয়ু, অচুম্বা মমল ফংবিয়ু।',
    easyBooking: 'লাইনা বুক তৌবা',
    noQueues: 'শাংলবা পরেল লৈরোই',
    fairPrices: 'অচুম্বা মমল',
    transparentMSP: 'শেংলবা এমএসপি',
    empowered: 'পাঙ্গল লৈরবা লৌমি',
    digitalHassleFree: 'ডিজিটেল অমসুং লাইবা',
    welcomeTo: 'তরাম্না ওকচরি',
    signInGoogleDesc: 'হৌননবগীদমক গুগল একাউন্টনা সাইন ইন তৌবিয়ু',
    continueWithGoogle: 'গুগলগা লোয়ননা মাংলোইশিল্লো',
    instantDemoLogin: 'খুদক্তা ডেমো লগইন (১-টেপ)',
    or: 'নত্রগা',
    securedBy: 'Google অমসুং Firebase না ঙাকশেনবা',
    transparent: 'শেংলবা',
    getFairPricesMsp: 'এমএসপিগা লোয়ননা\nঅচুম্বা মমল ফংবিয়ু',
    bookMandiSlotsInMin: 'মিনিট খরাদা মান্দি\nস্লট বুক তৌবিয়ু',
    digitalServicesEveryFarmer: 'লৌমি খুদিংমক্কীদমক\nডিজিটেল থৌগল',
    termsAgreement: 'মাংলোইশিল্লদুনা, অদোম্না য়ানরে',
    termsOfService: 'থৌগrollingগী চৎন-পথাপ',
    privacyPolicy: 'লোনচৎ ঙাকপগী নীতি',
    chooseLanguage: 'লোন খনবিয়ু',
    selectPreferredLang: 'অদোমগী পামজবা লোন খনবিয়ু',
    skip: 'থাদ্দোকউ',
    next: 'মখা তাবা',
    getStarted: 'হৌবিয়ু',
    onboarding1Title: 'পরেন্দি লেপ্তনা মান্দিদা',
    onboarding1Highlight: 'স্লট বুক তৌবিয়ু',
    onboarding1Desc: 'মতৌ চন্না মতম কনবিয়ু, মান্দি চংনবগী স্লট লাইনা বুক তৌবিয়ু।',
    onboarding2Title: 'ডিজিটেল চাউবা,',
    onboarding2Highlight: 'খোঙজেল য়াংনা এমএসপি পেমেন্ট',
    onboarding2Desc: 'অচুম্বা চাউবা, করিগুম্বা ককপদবা য়াওদনা বেঙ্ক একাউন্টতা হকথেংননা পেমেন্ট।',
    onboarding3Title: 'লাইভ পরেল',
    onboarding3Highlight: 'মোবাইলদা লাইভ য়েংশিনবা',
    onboarding3Desc: 'টোকেনগী মফম অমসুং ঙাইবগী মতম মোবাইলদা হকথেংননা য়েংবিয়ু।',
    onboarding4Title: 'লৈঙাক্কী স্কিম অমসুং',
    onboarding4Highlight: 'ডিজিলাকার কেৱাইসি',
    onboarding4Desc: 'লৈঙাক্কী স্কিমশিংগী মরিক চুম্বা পাউ অমসুং লাইনা ডিজিটেল চেক তৌবা।',
    greetingNamaste: 'খুরুমজরি',
    goodToSeeYou: 'অদোমগা অমুক হন্না উন্নবদা নুংঙাই',
    makeFarmingRewarding: 'লৌ-উ শিং-উবু হেন্না কান্নবা ওইহনসি।',
    farmerSlogan: '🌾 লৌমিগী হূম্লবা, লৈবাক্কী শক্তি 🌾',
    activeBookings: 'এক্টিভ বুকিং',
    queuePosition: 'পরেন্দিগী মফম',
    pendingPayments: 'ফংদ্রিবা শেল',
    totalProcured: 'পুন্না লৈরবা পোত্থোক',
    spotlightActive: 'এক্টিভ বুকিং',
    spotlightCompleted: 'লৈবা লোইশিনখ্রে',
    viewAll: 'ময়াম য়েংবিয়ু ›',
    noActiveBookings: 'এক্টিভ বুকিং অমত্তা লৈতে',
    noActiveBookingsDesc: 'অদোম্না হৌজিকফাওবা মান্দি স্লট বুক তৌদ্রি। অনৌবা স্লট বুক তৌবিয়ু।',
    bookNewSlot: '🌱 অনৌবা স্লট বুক তৌবিয়ু',
    quickActions: 'খোঙজেল য়াংবা থৌগল',
    bookSlot: 'স্লট বুকিং',
    liveQueue: 'লাইভ পরেল',
    myPayments: 'ঐহাক্কী শেল',
    govtSchemes: 'লৈঙাক্কী স্কিম',
    mspRates: 'এমএসপি মমল (2026-27)',




  },
};

const COMMON_STRINGS: Record<string, Record<string, string>> = {
  hi: {
    'Home': 'होम',
    'Bookings': 'बुकिंग्स',
    'Book Slot': 'स्लॉट बुक करें',
    'Scan QR': 'QR स्कैन',
    'Scan': 'स्कैन',
    'Live Queue': 'लाइव कतार',
    'Reports': 'रिपोर्ट्स',
    'Analytics': 'एनालिटिक्स',
    'Mandi Hubs': 'मंडी हब्स',
    'MSP Master': 'MSP मास्टर',
    'Centres': 'मंडी केंद्र',
    'Payments': 'भुगतान',
    'Profile': 'प्रोफाइल',
    'MANDI DESK': 'मंडी डेस्क',
    'Gate QR Check-In': 'गेट QR चेक-इन',
    'Intake & Weighment': 'आवक एवं तौल',
    'Operator Daily Report': 'ऑपरेटर दैनिक रिपोर्ट',
    'Deep Analytics Hub': 'गहन एनालिटिक्स हब',
    'Mandi Centres Master': 'मंडी केंद्र मास्टर',
    'MSP Crops Master': 'MSP फसल मास्टर',
    'Today\'s Operational Overview': 'आज का परिचालन विवरण',
    'Checked-In': 'चेक-इन',
    'In Queue': 'कतार में',
    'Processed Today': 'आज संसाधित',
    'Avg Wait Time': 'औसत प्रतीक्षा समय',
    'Desk Quick Actions': 'डेस्क त्वरित सेवाएं',
    'Process Next': 'अगला संसाधित करें',
    'Weigh & Form J': 'तौल और फॉर्म जे',
    'View Queue': 'कतार देखें',
    'Yard Call Board': 'यार्ड कॉल बोर्ड',
    'Daily Report': 'दैनिक रिपोर्ट',
    'Intake Summary & PDF': 'आवक सारांश और PDF',
    'DBT Payouts Log': 'DBT भुगतान लॉग',
    'Desk Stats': 'डेस्क आंकड़े',
    'Speed & Performance': 'गति एवं प्रदर्शन',
    'Recent Processed Farmers': 'हाल ही में संसाधित किसान',
    'Last 10 Completed': 'पिछले 10 पूर्ण',
    'Pan-India Mandi Control': 'अखिल भारतीय मंडी नियंत्रण',
    'Dept. of Food & Public Distribution': 'खाद्य एवं सार्वजनिक वितरण विभाग',
    'NATIONAL LIVE MONITORING': 'राष्ट्रीय लाइव निगरानी',
    'Key Operational Metrics (Pan-India)': 'मुख्य परिचालन मेट्रिक्स (अखिल भारतीय)',
    'Total Mandi Centres': 'कुल मंडी केंद्र',
    'Active Centres Today': 'आज सक्रिय केंद्र',
    'Farmers Registered': 'पंजीकृत किसान',
    'Today\'s Footfall': 'आज का फुटफॉल',
    'Revenue Processed': 'संसाधित राजस्व',
    'Avg Mandi Wait Time': 'औसत मंडी प्रतीक्षा समय',
    'State-Wise Activity Heat Map': 'राज्यवार गतिविधि हीट मैप',
    'Real-Time Mandi Alerts Feed': 'रीयल-टाइम मंडी अलर्ट',
    'Top 5 Mandis Today (By Volume)': 'आज की शीर्ष 5 मंडियां (मात्रा अनुसार)',
    'Recent Admin Actions Audit Trail': 'हाल की व्यवस्थापक गतिविधियां',
  },
  pa: {
    'Home': 'ਹੋਮ',
    'Bookings': 'ਬੁਕਿੰਗਾਂ',
    'Book Slot': 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    'Scan QR': 'QR ਸਕੈਨ',
    'Scan': 'ਸਕੈਨ',
    'Live Queue': 'ਲਾਈਵ ਕਤਾਰ',
    'Reports': 'ਰਿਪੋਰਟਾਂ',
    'Analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'Mandi Hubs': 'ਮੰਡੀ ਹੱਬ',
    'MSP Master': 'MSP ਮਾਸਟਰ',
    'Centres': 'ਕੇਂਦਰ',
    'Payments': 'ਭੁਗਤਾਨ',
    'Profile': 'ਪ੍ਰੋਫਾਈਲ',
    'MANDI DESK': 'ਮੰਡੀ ਡੈਸਕ',
    'Gate QR Check-In': 'ਗੇਟ QR ਚੈੱਕ-ਇਨ',
    'Intake & Weighment': 'ਤੋਲ ਅਤੇ ਆਮਦ',
    'Operator Daily Report': 'ਆਪਰੇਟਰ ਰੋਜ਼ਾਨਾ ਰਿਪੋਰਟ',
    'Deep Analytics Hub': 'ਐਨਾਲਿਟਿਕਸ ਹੱਬ',
    'Mandi Centres Master': 'ਮੰਡੀ ਕੇਂਦਰ ਮਾਸਟਰ',
    'MSP Crops Master': 'MSP ਫ਼ਸਲ ਮਾਸਟਰ',
    'Checked-In': 'ਚੈੱਕ-ਇਨ',
    'In Queue': 'ਕਤਾਰ ਵਿੱਚ',
    'Processed Today': 'ਅੱਜ ਪ੍ਰੋਸੈਸ ਕੀਤਾ',
    'Avg Wait Time': 'ਔਸਤ ਉਡੀਕ ਸਮਾਂ',
  },
  mr: {
    'Home': 'मुख्यपृष्ठ',
    'Bookings': 'बुकिंग',
    'Book Slot': 'स्लॉट बुक करा',
    'Scan QR': 'QR स्कॅन',
    'Scan': 'स्कॅन',
    'Live Queue': 'थेट रांग',
    'Reports': 'अहवाल',
    'Analytics': 'विश्लेषण',
    'Mandi Hubs': 'मार्केट हब',
    'MSP Master': 'MSP मास्टर',
    'Centres': 'केंद्रे',
    'Payments': 'पेमेंट्स',
    'Profile': 'प्रोफाइल',
    'MANDI DESK': 'मंडी डेस्क',
    'Gate QR Check-In': 'गेट QR चेक-इन',
    'Intake & Weighment': 'वजन आणि आवक',
    'Checked-In': 'चेक-इन',
    'In Queue': 'रांगेत',
    'Processed Today': 'आज पूर्ण झाले',
    'Avg Wait Time': 'सरासरी प्रतीक्षा वेळ',
  },
  gu: {
    'Home': 'હોમ',
    'Bookings': 'બુકિંગ',
    'Book Slot': 'સ્લોટ બુક કરો',
    'Scan QR': 'QR સ્કેન',
    'Scan': 'સ્કેન',
    'Live Queue': 'લાઈવ કતાર',
    'Reports': 'અહેવાલો',
    'Analytics': 'વિશ્લેષણ',
    'Mandi Hubs': 'માર્કેટ હબ',
    'MSP Master': 'MSP માસ્ટર',
    'Centres': 'કેન્દ્રો',
    'Payments': 'ચુકવણી',
    'Profile': 'પ્રોફાઇલ',
    'MANDI DESK': 'મંડી ડેસ્ક',
    'Gate QR Check-In': 'ગેટ QR ચેક-ઇન',
    'Intake & Weighment': 'વજન અને આવક',
    'Checked-In': 'ચેક-ઇન',
    'In Queue': 'કતારમાં',
    'Processed Today': 'આજે પ્રોસેસ થયેલ',
    'Avg Wait Time': 'સરેરાશ રાહ જોવાનો સમય',
  },
  te: {
    'Home': 'హోమ్',
    'Bookings': 'బుకింగ్స్',
    'Book Slot': 'స్లాట్ బుక్ చేయండి',
    'Scan QR': 'QR స్కాన్',
    'Scan': 'స్కాన్',
    'Live Queue': 'లైవ్ క్యూ',
    'Reports': 'నివేదికలు',
    'Analytics': 'విశ్లేషణ',
    'Mandi Hubs': 'మార్కెట్ హబ్‌లు',
    'MSP Master': 'MSP మాస్టర్',
    'Centres': 'కేంద్రాలు',
    'Payments': 'చెల్లింపులు',
    'Profile': 'ప్రొఫైల్',
    'MANDI DESK': 'మండి డెస్క్',
    'Checked-In': 'చెక్-ఇన్',
    'In Queue': 'క్యూలో ఉంది',
    'Processed Today': 'ఈరోజు ప్రాసెస్ చేయబడింది',
    'Avg Wait Time': 'సగటు నిరీక్షణ సమయం',
  },
  bn: {
    'Home': 'হোম',
    'Bookings': 'বুকিং',
    'Book Slot': 'স্লট বুক করুন',
    'Scan QR': 'QR স্ক্যান',
    'Scan': 'স্ক্যান',
    'Live Queue': 'লাইভ সারি',
    'Reports': 'প্রতিবেদন',
    'Analytics': 'বিশ্লেষণ',
    'Mandi Hubs': 'মান্ডি হাব',
    'MSP Master': 'MSP মাস্টার',
    'Centres': 'কেন্দ্রগুলি',
    'Payments': 'পেমেন্ট',
    'Profile': 'প্রোফাইল',
    'MANDI DESK': 'মান্ডি ডেস্ক',
    'Checked-In': 'চেক-ইন',
    'In Queue': 'সারিতে',
    'Processed Today': 'আজ প্রক্রিয়াধীন',
    'Avg Wait Time': 'গড় অপেক্ষার সময়',
  },
  ta: {
    'Home': 'முகப்பு',
    'Bookings': 'முன்பதிவுகள்',
    'Book Slot': 'ஸ்லாட் பதிவு செய்',
    'Scan QR': 'QR ஸ்கேன்',
    'Scan': 'ஸ்கேன்',
    'Live Queue': 'நேரலை வரிசை',
    'Reports': 'அறிக்கைகள்',
    'Analytics': 'பகுப்பாய்வு',
    'Mandi Hubs': 'மண்டி மையங்கள்',
    'MSP Master': 'MSP மாஸ்டர்',
    'Centres': 'மையங்கள்',
    'Payments': 'பணம் செலுத்துதல்',
    'Profile': 'சுயவிவரம்',
    'MANDI DESK': 'மண்டி டெஸ்க்',
    'Checked-In': 'செக்-இன்',
    'In Queue': 'வரிசையில்',
    'Processed Today': 'இன்று முடிந்தது',
    'Avg Wait Time': 'சராசரி காத்திருப்பு நேரம்',
  },
  kn: {
    'Home': 'ಮುಖಪುಟ',
    'Bookings': 'ಬುಕಿಂಗ್‌ಗಳು',
    'Book Slot': 'ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ',
    'Scan QR': 'QR ಸ್ಕ್ಯಾನ್',
    'Scan': 'ಸ್ಕ್ಯಾನ್',
    'Live Queue': 'ಲೈವ್ ಸರತಿ',
    'Reports': 'ವರದಿಗಳು',
    'Analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'Mandi Hubs': 'ಮಂಡಿ ಹಬ್',
    'MSP Master': 'MSP ಮಾಸ್ಟರ್',
    'Centres': 'ಕೇಂದ್ರಗಳು',
    'Payments': 'ಪಾವತಿಗಳು',
    'Profile': 'ಪ್ರೊಫೈಲ್',
    'MANDI DESK': 'ಮಂಡಿ ಡೆಸ್ಕ್',
    'Checked-In': 'ಚೆಕ್-ಇನ್',
    'In Queue': 'ಸರತಿಯಲ್ಲಿ',
    'Processed Today': 'ಇಂದು ಪ್ರಕ್ರಿಯೆಗೊಂಡಿದೆ',
    'Avg Wait Time': 'ಸರಾಸರಿ ಕಾಯುವ ಸಮಯ',
  },
  ml: {
    'Home': 'ഹോം',
    'Bookings': 'ബുക്കിംഗുകൾ',
    'Book Slot': 'സ്ലോട്ട് ബുക്ക് ചെയ്യുക',
    'Scan QR': 'QR സ്കാൻ',
    'Scan': 'സ്കാൻ',
    'Live Queue': 'തത്സമയ ക്യൂ',
    'Reports': 'റിപ്പോർട്ടുകൾ',
    'Analytics': 'വിശകലനം',
    'Mandi Hubs': 'മാർക്കറ്റ് ഹബ്ബുകൾ',
    'MSP Master': 'MSP മാസ്റ്റർ',
    'Centres': 'കേന്ദ്രങ്ങൾ',
    'Payments': 'പേയ്മെന്റുകൾ',
    'Profile': 'പ്രൊഫൈൽ',
    'MANDI DESK': 'മണ്ടി ഡെസ്ക്',
    'Checked-In': 'ചെക്ക്-ഇൻ',
    'In Queue': 'ക്യൂവിൽ',
    'Processed Today': 'ഇന്ന് പ്രോസസ്സ് ചെയ്തത്',
    'Avg Wait Time': 'ശരാശരി കാത്തിരിപ്പ് സമയം',
  },
  or: {
    'Home': 'ହୋମ',
    'Bookings': 'ବୁକିଂ',
    'Book Slot': 'ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ',
    'Scan QR': 'QR ସ୍କାନ',
    'Scan': 'ସ୍କାନ',
    'Live Queue': 'ଲାଇଭ୍ ଧାଡ଼ି',
    'Reports': 'ରିପୋର୍ଟ',
    'Analytics': 'ବିଶ୍ଳେଷଣ',
    'Mandi Hubs': 'ମଣ୍ଡି ହବ୍',
    'MSP Master': 'MSP ମାଷ୍ଟର',
    'Centres': 'କେନ୍ଦ୍ରଗୁଡ଼ିକ',
    'Payments': 'ଦେୟ',
    'Profile': 'ପ୍ରୋଫାଇଲ୍',
    'MANDI DESK': 'ମଣ୍ଡି ଡେସ୍କ',
    'Checked-In': 'ଚେକ୍-ଇନ୍',
    'In Queue': 'ଧାଡ଼ିରେ',
    'Processed Today': 'ଆଜି ପ୍ରକ୍ରିୟାକରଣ',
    'Avg Wait Time': 'ହାରାହାରି ଅପେକ୍ଷା ସମୟ',
  },
};

interface LanguageContextType {
  currentLanguage: string;
  activeLanguageInfo: IndianLanguage;
  setLanguage: (langCode: string) => Promise<void>;
  t: (keyOrText: TranslationKey | string) => string;
  translateDynamic: (text: string) => Promise<string>;
  isReady: boolean;
  version: number;
}

const defaultLangInfo = INDIAN_LANGUAGES[0];

const LanguageContext = createContext<LanguageContextType>({
  currentLanguage: 'en',
  activeLanguageInfo: defaultLangInfo,
  setLanguage: async () => {},
  t: (keyOrText: TranslationKey | string) => keyOrText,
  translateDynamic: async (text: string) => text,
  isReady: false,
  version: 0,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<string>('en');
  const [isReady, setIsReady] = useState(false);
  const [version, setVersion] = useState(0);

  useEffect(() => {
    async function init() {
      try {
        const saved = await Storage.getItem<string>('kisan_lang');
        if (saved && (saved in TRANSLATIONS || INDIAN_LANGUAGES.some((l) => l.code === saved))) {
          setCurrentLanguageState(saved);
          await initLanguageCache(saved);
        }
      } catch {
        // fallback to en
      } finally {
        setIsReady(true);
      }
    }
    init();
  }, []);

  const changeLang = async (langCode: string) => {
    setCurrentLanguageState(langCode);
    await Storage.setItem('kisan_lang', langCode);
    await initLanguageCache(langCode);
    setVersion((v) => v + 1);
  };

  const activeLanguageInfo =
    INDIAN_LANGUAGES.find((l) => l.code === currentLanguage) || INDIAN_LANGUAGES[0];

  const t = (keyOrText: TranslationKey | string): string => {
    if (!keyOrText || currentLanguage === 'en') {
      return keyOrText;
    }

    // 1. Direct language dictionary lookup
    const langDict = TRANSLATIONS[currentLanguage];
    if (langDict && (langDict as any)[keyOrText]) {
      return (langDict as any)[keyOrText];
    }

    // 2. Common phrase dictionary lookup (e.g. 'Home', 'Scan QR', 'Reports', etc.)
    const commonDict = COMMON_STRINGS[currentLanguage];
    if (commonDict && commonDict[keyOrText]) {
      return commonDict[keyOrText];
    }

    // 3. Dynamic translation cache (from Google Translate API)
    const cached = getCachedTranslation(keyOrText, currentLanguage);
    if (cached) {
      return cached;
    }

    // 4. Trigger dynamic Google Translate in background without blocking UI
    translateText(keyOrText, currentLanguage).then((translated) => {
      if (translated && translated !== keyOrText) {
        setVersion((v) => v + 1);
      }
    });

    // 5. Hindi fallback for Indian languages if exact key is missing
    if (COMMON_STRINGS.hi && COMMON_STRINGS.hi[keyOrText]) {
      return COMMON_STRINGS.hi[keyOrText];
    }
    if (TRANSLATIONS.hi && (TRANSLATIONS.hi as any)[keyOrText]) {
      return (TRANSLATIONS.hi as any)[keyOrText];
    }

    // 6. English master fallback
    return (TRANSLATIONS.en as any)?.[keyOrText] || keyOrText;
  };

  const translateDynamic = async (text: string): Promise<string> => {
    return translateText(text, currentLanguage);
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        activeLanguageInfo,
        setLanguage: changeLang,
        t,
        translateDynamic,
        isReady,
        version,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage() {
  return useContext(LanguageContext);
}

/**
 * Auto-Translating Text Component for Mobile:
 * Developers can simply write:
 * <T style={styles.anyStyle}>Any English text</T>
 * and it automatically translates via Google Translate into any of the 22 Indian regional languages!
 */
export const T: React.FC<TextProps & { children: string }> = ({ children, style, ...rest }) => {
  const { t } = useLanguage();
  return (
    <Text style={style} {...rest}>
      {typeof children === 'string' ? t(children) : children}
    </Text>
  );
};
