import Storage from "./storage";

export interface IndianLanguage {
  code: string;
  name: string;
  nativeName: string;
  states: string;
  shortTag: string;
  avatarColor: string;
  region: "national" | "north" | "south" | "east" | "west";
  isPopular?: boolean;
}

export const INDIAN_LANGUAGES: IndianLanguage[] = [
  {
    code: "en",
    name: "English",
    nativeName: "English",
    states: "All India (Official Default)",
    shortTag: "EN",
    avatarColor: "#1E293B",
    region: "national",
    isPopular: true,
  },
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    states: "UP, MP, Bihar, Rajasthan, Haryana",
    shortTag: "हि",
    avatarColor: "#EA580C",
    region: "north",
    isPopular: true,
  },
  {
    code: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    states: "Punjab, Chandigarh, Haryana",
    shortTag: "ਪੰ",
    avatarColor: "#EA580C",
    region: "north",
    isPopular: true,
  },
  {
    code: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    states: "Maharashtra, Goa",
    shortTag: "म",
    avatarColor: "#E11D48",
    region: "west",
    isPopular: true,
  },
  {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    states: "Gujarat, Dadra & Nagar Haveli",
    shortTag: "ગુ",
    avatarColor: "#0284C7",
    region: "west",
    isPopular: true,
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    states: "Andhra Pradesh, Telangana",
    shortTag: "తె",
    avatarColor: "#6366F1",
    region: "south",
    isPopular: true,
  },
  {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    states: "West Bengal, Tripura, Assam",
    shortTag: "বা",
    avatarColor: "#059669",
    region: "east",
    isPopular: true,
  },
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    states: "Tamil Nadu, Puducherry",
    shortTag: "த",
    avatarColor: "#B91C1C",
    region: "south",
    isPopular: true,
  },
  {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    states: "Karnataka",
    shortTag: "ಕ",
    avatarColor: "#B45309",
    region: "south",
    isPopular: true,
  },
  {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    states: "Kerala, Lakshadweep",
    shortTag: "മ",
    avatarColor: "#0D9488",
    region: "south",
    isPopular: true,
  },
  {
    code: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
    states: "Odisha",
    shortTag: "ଓ",
    avatarColor: "#7C3AED",
    region: "east",
    isPopular: true,
  },
  {
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    states: "Assam",
    shortTag: "অ",
    avatarColor: "#65A30D",
    region: "east",
    isPopular: true,
  },
  {
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
    states: "Jammu & Kashmir, Telangana, UP",
    shortTag: "اردو",
    avatarColor: "#065F46",
    region: "national",
    isPopular: true,
  },
  {
    code: "bho",
    name: "Bhojpuri",
    nativeName: "भोजपुरी",
    states: "Bihar, Eastern UP, Jharkhand",
    shortTag: "भोज",
    avatarColor: "#C2410C",
    region: "north",
    isPopular: true,
  },
  {
    code: "mai",
    name: "Maithili",
    nativeName: "मैथिली",
    states: "Bihar, Mithila, Jharkhand",
    shortTag: "मै",
    avatarColor: "#BE185D",
    region: "north",
  },
  {
    code: "sa",
    name: "Sanskrit",
    nativeName: "संस्कृतम्",
    states: "Classical / Pan-India",
    shortTag: "सं",
    avatarColor: "#D97706",
    region: "national",
  },
  {
    code: "kok",
    name: "Konkani",
    nativeName: "कोंकणी",
    states: "Goa, Coastal Maharashtra, Karnataka",
    shortTag: "कों",
    avatarColor: "#2563EB",
    region: "west",
  },
  {
    code: "sd",
    name: "Sindhi",
    nativeName: "سنڌي",
    states: "Gujarat, Rajasthan, Maharashtra",
    shortTag: "سن",
    avatarColor: "#3F3F46",
    region: "west",
  },
  {
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    states: "Sikkim, West Bengal (Darjeeling)",
    shortTag: "ने",
    avatarColor: "#0284C7",
    region: "east",
  },
  {
    code: "doi",
    name: "Dogri",
    nativeName: "डोगरी",
    states: "Jammu & Kashmir, Himachal Pradesh",
    shortTag: "डो",
    avatarColor: "#6D28D9",
    region: "north",
  },
  {
    code: "ks",
    name: "Kashmiri",
    nativeName: "کٲشُر",
    states: "Jammu & Kashmir Valley",
    shortTag: "کٲ",
    avatarColor: "#3730A3",
    region: "north",
  },
  {
    code: "mni-Mtei",
    name: "Manipuri (Meitei)",
    nativeName: "মৈতৈলোন্",
    states: "Manipur",
    shortTag: "মৈ",
    avatarColor: "#831843",
    region: "east",
  },
];

export async function getCurrentLanguage(): Promise<string> {
  const saved = await Storage.getItem<string>("kisan_lang");
  return saved || "en";
}

export async function setLanguage(langCode: string): Promise<void> {
  await Storage.setItem("kisan_lang", langCode);
}
